module.exports = {
	list: [{
		"letter": "A",
		"data": [{
			"name": "鞍山市",
			"city_pinyin": "anshan",
			"city_id": 210300,
			"py": "as"
		}, {
			"name": "安庆市",
			"city_pinyin": "anqing",
			"city_id": 340800,
			"py": "aq"
		}, {
			"name": "安阳市",
			"city_pinyin": "anyang",
			"city_id": 410500,
			"py": "ay"
		}, {
			"name": "澳门",
			"city_pinyin": "aomen",
			"city_id": 820001,
			"py": "am"
		}, ]
	}, {
		"letter": "B",
		"data": [{
			"name": "北京市",
			"city_pinyin": "beijing",
			"city_id": 110100,
			"py": "bj"
		}, {
			"name": "保定市",
			"city_pinyin": "baoding",
			"city_id": 130600,
			"py": "bd"
		}, {
			"name": "包头市",
			"city_pinyin": "baotou",
			"city_id": 150200,
			"py": "bt"
		}, {
			"name": "巴彦淖尔市",
			"city_pinyin": "bayannaoer",
			"city_id": 150800,
			"py": "byne"
		}, {
			"name": "本溪市",
			"city_pinyin": "benxi",
			"city_id": 210500,
			"py": "bx"
		}, {
			"name": "白山市",
			"city_pinyin": "baishan",
			"city_id": 220600,
			"py": "bs"
		}, {
			"name": "白城市",
			"city_pinyin": "baicheng",
			"city_id": 220800,
			"py": "bc"
		}, {
			"name": "蚌埠市",
			"city_pinyin": "bengbu",
			"city_id": 340300,
			"py": "bb"
		}, {
			"name": "亳州市",
			"city_pinyin": "bozhou",
			"city_id": 341600,
			"py": "bz"
		}, {
			"name": "滨州市",
			"city_pinyin": "binzhou",
			"city_id": 371600,
			"py": "bz"
		}, {
			"name": "北海市",
			"city_pinyin": "beihai",
			"city_id": 450500,
			"py": "bh"
		}, {
			"name": "百色市",
			"city_pinyin": "baise",
			"city_id": 451000,
			"py": "bs"
		}, {
			"name": "巴中市",
			"city_pinyin": "bazhong",
			"city_id": 511900,
			"py": "bz"
		}, {
			"name": "毕节地区",
			"city_pinyin": "bijie",
			"city_id": 520500,
			"py": "bj"
		}, {
			"name": "保山市",
			"city_pinyin": "baoshan",
			"city_id": 530500,
			"py": "bs"
		}, {
			"name": "宝鸡市",
			"city_pinyin": "baoji",
			"city_id": 610300,
			"py": "bj"
		}, {
			"name": "白银市",
			"city_pinyin": "baiyin",
			"city_id": 620400,
			"py": "by"
		}, ]
	}, {
		"letter": "C",
		"data": [{
			"name": "沧州市",
			"city_pinyin": "cangzhou",
			"city_id": 130900,
			"py": "cz"
		}, {
			"name": "长春市",
			"city_pinyin": "changchun",
			"city_id": 220100,
			"py": "cc"
		}, {
			"name": "常德市",
			"city_pinyin": "changde",
			"city_id": 430700,
			"py": "cd"
		}, {
			"name": "昌都市",
			"city_pinyin": "changdu",
			"city_id": 542100,
			"py": "cd"
		}, {
			"name": "长葛市市",
			"city_pinyin": "changgeshi",
			"city_id": 411082,
			"py": "cgs"
		}, {
			"name": "昌吉市",
			"city_pinyin": "changji",
			"city_id": 652301,
			"py": "cj"
		}, {
			"name": "昌吉回族自治州",
			"city_pinyin": "changjihuizuzizhizhou",
			"city_id": 652300,
			"py": "cjhzzzz"
		}, {
			"name": "长乐市",
			"city_pinyin": "changleshi",
			"city_id": 350182,
			"py": "cls"
		}, {
			"name": "常宁市",
			"city_pinyin": "changningshi",
			"city_id": 430482,
			"py": "cns"
		}, {
			"name": "长沙市",
			"city_pinyin": "changsha",
			"city_id": 430100,
			"py": "cs"
		}, {
			"name": "常熟市",
			"city_pinyin": "changshu",
			"city_id": 320581,
			"py": "cs"
		}, {
			"name": "昌邑市",
			"city_pinyin": "changyishi",
			"city_id": 370786,
			"py": "cys"
		}, {
			"name": "长治市",
			"city_pinyin": "changzhishi",
			"city_id": 140400,
			"py": "czs"
		}, {
			"name": "常州市",
			"city_pinyin": "changzhou",
			"city_id": 320400,
			"py": "cz"
		}, {
			"name": "巢湖市",
			"city_pinyin": "chaohu",
			"city_id": 340181,
			"py": "ch"
		}, {
			"name": "朝阳市",
			"city_pinyin": "chaoyang",
			"city_id": 211300,
			"py": "zy"
		}, {
			"name": "潮州市",
			"city_pinyin": "chaozhou",
			"city_id": 445100,
			"py": "cz"
		}, {
			"name": "承德市",
			"city_pinyin": "chengde",
			"city_id": 130800,
			"py": "cd"
		}, {
			"name": "成都市",
			"city_pinyin": "chengdu",
			"city_id": 510100,
			"py": "cd"
		}, {
			"name": "郴州市",
			"city_pinyin": "chenzhou",
			"city_id": 431000,
			"py": "cz"
		}, {
			"name": "赤壁市",
			"city_pinyin": "chibishi",
			"city_id": 421281,
			"py": "cbs"
		}, {
			"name": "赤峰市",
			"city_pinyin": "chifeng",
			"city_id": 150400,
			"py": "cf"
		}, {
			"name": "池州市",
			"city_pinyin": "chizhou",
			"city_id": 341700,
			"py": "cz"
		}, {
			"name": "重庆市",
			"city_pinyin": "chongqing",
			"city_id": 500100,
			"py": "cq"
		}, {
			"name": "崇州市",
			"city_pinyin": "chongzhoushi",
			"city_id": 510184,
			"py": "czs"
		}, {
			"name": "崇左市",
			"city_pinyin": "chongzuo",
			"city_id": 451400,
			"py": "cz"
		}, {
			"name": "楚雄",
			"city_pinyin": "chuxiong",
			"city_id": 532301,
			"py": "cx"
		}, {
			"name": "楚雄彝族自治州",
			"city_pinyin": "chuxiongyizuzizhizhou",
			"city_id": 532300,
			"py": "cxyzzzz"
		}, {
			"name": "滁州市",
			"city_pinyin": "chuzhou",
			"city_id": 341100,
			"py": "cz"
		}, {
			"name": "从化市",
			"city_pinyin": "conghuashi",
			"city_id": 440184,
			"py": "chs"
		}, ]
	}, {
		"letter": "D",
		"data": [{
			"name": "大安市",
			"city_pinyin": "daanshi",
			"city_id": 220882,
			"py": "das"
		}, {
			"name": "大丰市",
			"city_pinyin": "dafengshi",
			"city_id": 320982,
			"py": "dfs"
		}, {
			"name": "大连市",
			"city_pinyin": "dalian",
			"city_id": 210200,
			"py": "dl"
		}, {
			"name": "大理白族自治州",
			"city_pinyin": "dalibaizuzizhiqu",
			"city_id": 532900,
			"py": "dlbzzzz"
		}, {
			"name": "丹东市",
			"city_pinyin": "dandong",
			"city_id": 210600,
			"py": "dd"
		}, {
			"name": "当阳市",
			"city_pinyin": "dangyangshi",
			"city_id": 420582,
			"py": "dys"
		}, {
			"name": "丹江口市",
			"city_pinyin": "danjiangkoushi",
			"city_id": 420381,
			"py": "djks"
		}, {
			"name": "丹阳市",
			"city_pinyin": "danyangshi",
			"city_id": 321181,
			"py": "dys"
		}, {
			"name": "儋州市",
			"city_pinyin": "danzhou",
			"city_id": 469003,
			"py": "dz"
		}, {
			"name": "大庆市",
			"city_pinyin": "daqing",
			"city_id": 230600,
			"py": "dq"
		}, {
			"name": "大石桥市",
			"city_pinyin": "dashiqiaoshi",
			"city_id": 210882,
			"py": "dsqs"
		}, {
			"name": "大同市",
			"city_pinyin": "datong",
			"city_id": 140200,
			"py": "dt"
		}, {
			"name": "大兴安岭地区",
			"city_pinyin": "daxinganlingdiqu",
			"city_id": 232700,
			"py": "dxaldq"
		}, {
			"name": "大冶市",
			"city_pinyin": "dayeshi",
			"city_id": 420281,
			"py": "dys"
		}, {
			"name": "达州市",
			"city_pinyin": "dazhou",
			"city_id": 511700,
			"py": "dz"
		}, {
			"name": "德宏傣族景颇族自治州",
			"city_pinyin": "dehongdaizujingpozuzizhizhou",
			"city_id": 533100,
			"py": "dhdzjpzzzz"
		}, {
			"name": "德惠市",
			"city_pinyin": "dehuishi",
			"city_id": 220183,
			"py": "dhs"
		}, {
			"name": "德令哈市",
			"city_pinyin": "delinghashi",
			"city_id": 632802,
			"py": "dlhs"
		}, {
			"name": "登封市",
			"city_pinyin": "dengfengshi",
			"city_id": 410185,
			"py": "dfs"
		}, {
			"name": "邓州市",
			"city_pinyin": "dengzhoushi",
			"city_id": 411381,
			"py": "dzs"
		}, {
			"name": "德庆市",
			"city_pinyin": "deqing",
			"city_id": 441226,
			"py": "dq"
		}, {
			"name": "德阳市",
			"city_pinyin": "deyang",
			"city_id": 510600,
			"py": "dy"
		}, {
			"name": "德州市",
			"city_pinyin": "dezhou",
			"city_id": 371400,
			"py": "dz"
		}, {
			"name": "调兵山市",
			"city_pinyin": "diaobingshanshi",
			"city_id": 211281,
			"py": "dbss"
		}, {
			"name": "定西市",
			"city_pinyin": "dingxi",
			"city_id": 621100,
			"py": "dx"
		}, {
			"name": "定州市",
			"city_pinyin": "dingzhoushi",
			"city_id": 130682,
			"py": "dzs"
		}, {
			"name": "迪庆藏族自治州",
			"city_pinyin": "diqingzangzuzizhizhou",
			"city_id": 533400,
			"py": "dqzzzzz"
		}, {
			"name": "东方市",
			"city_pinyin": "dongfang",
			"city_id": 469007,
			"py": "df"
		}, {
			"name": "东港市",
			"city_pinyin": "donggangshi",
			"city_id": 210681,
			"py": "dgs"
		}, {
			"name": "东莞市",
			"city_pinyin": "dongguan",
			"city_id": 441900,
			"py": "dg"
		}, {
			"name": "东台市",
			"city_pinyin": "dongtaishi",
			"city_id": 320981,
			"py": "dts"
		}, {
			"name": "东营市",
			"city_pinyin": "dongying",
			"city_id": 370500,
			"py": "dy"
		}, {
			"name": "都江堰市",
			"city_pinyin": "doujiangyanshi",
			"city_id": 510181,
			"py": "djys"
		}, {
			"name": "敦化市",
			"city_pinyin": "dunhuashi",
			"city_id": 222403,
			"py": "dhs"
		}, {
			"name": "都匀市",
			"city_pinyin": "duyunshi",
			"city_id": 522701,
			"py": "dys"
		}]
	}, {
		"letter": "E",
		"data": [{
			"name": "鄂尔多斯",
			"city_pinyin": "eerduosi",
			"city_id": 150600,
			"py": "eeds"
		}, {
			"name": "恩施土家族苗族自治州",
			"city_pinyin": "enshitujiazumiaozuzizhizhou",
			"city_id": 422800,
			"py": "estjzmzzzz"
		}, {
			"name": "二连浩特市",
			"city_pinyin": "erlianhaoteshi",
			"city_id": 152501,
			"py": "elhts"
		}, ]
	}, {
		"letter": "F",
		"data": [{
			"name": "抚顺市",
			"city_pinyin": "fushun",
			"city_id": 210400,
			"py": "fs"
		}, {
			"name": "阜新市",
			"city_pinyin": "fuxin",
			"city_id": 210900,
			"py": "fx"
		}, {
			"name": "阜阳市",
			"city_pinyin": "fuyang",
			"city_id": 341200,
			"py": "fy"
		}, {
			"name": "福州市",
			"city_pinyin": "fuzhou",
			"city_id": 350100,
			"py": "fz"
		}, {
			"name": "抚州市",
			"city_pinyin": "fuzhou",
			"city_id": 361000,
			"py": "fz"
		}, {
			"name": "防城港市",
			"city_pinyin": "fangchenggang",
			"city_id": 450600,
			"py": "fcg"
		}, {
			"name": "肥城市",
			"city_pinyin": "feichengshi",
			"city_id": 370983,
			"py": "fcs"
		}, {
			"name": "丰城市",
			"city_pinyin": "fengchengshi",
			"city_id": 360981,
			"py": "fcs"
		}, {
			"name": "凤城市",
			"city_pinyin": "fengchengshi",
			"city_id": 210682,
			"py": "fcs"
		}, {
			"name": "奉化市",
			"city_pinyin": "fenghuashi",
			"city_id": 330283,
			"py": "fhs"
		}, {
			"name": "丰镇市",
			"city_pinyin": "fengzhenshi",
			"city_id": 150981,
			"py": "fzs"
		}, {
			"name": "汾阳市",
			"city_pinyin": "fenyang",
			"city_id": 141182,
			"py": "fy"
		}, {
			"name": "佛山市",
			"city_pinyin": "foshan",
			"city_id": 440600,
			"py": "fs"
		}, {
			"name": "福安市",
			"city_pinyin": "fuanshi",
			"city_id": 350981,
			"py": "fas"
		}, {
			"name": "福鼎市",
			"city_pinyin": "fudingshi",
			"city_id": 350982,
			"py": "fds"
		}, {
			"name": "富锦市",
			"city_pinyin": "fujinshi",
			"city_id": 230882,
			"py": "fjs"
		}, {
			"name": "阜康市",
			"city_pinyin": "fukangshi",
			"city_id": 652302,
			"py": "fks"
		}, {
			"name": "福泉市",
			"city_pinyin": "fuquanshi",
			"city_id": 522702,
			"py": "fqs"
		}, ]
	}, {
		"letter": "G",
		"data": [{
			"name": "广州市",
			"city_pinyin": "guangzhou",
			"city_id": 440100,
			"py": "gz"
		}, {
			"name": "赣州市",
			"city_pinyin": "ganzhou",
			"city_id": 360700,
			"py": "gz"
		}, {
			"name": "桂林市",
			"city_pinyin": "guilin",
			"city_id": 450300,
			"py": "gl"
		}, {
			"name": "桂平市",
			"city_pinyin": "guipingshi",
			"city_id": 450881,
			"py": "gps"
		}, {
			"name": "贵溪市",
			"city_pinyin": "guixishi",
			"city_id": 360681,
			"py": "gxs"
		}, {
			"name": "贵阳市",
			"city_pinyin": "guiyang",
			"city_id": 520100,
			"py": "gy"
		}, {
			"name": "贵港市",
			"city_pinyin": "guigang",
			"city_id": 450800,
			"py": "gg"
		}, {
			"name": "广水市",
			"city_pinyin": "guangshuishi",
			"city_id": 421381,
			"py": "gss"
		}, {
			"name": "广元市",
			"city_pinyin": "guangyuan",
			"city_id": 510800,
			"py": "gy"
		}, {
			"name": "广安市",
			"city_pinyin": "guangan",
			"city_id": 511600,
			"py": "ga"
		}, {
			"name": "固原市",
			"city_pinyin": "guyuan",
			"city_id": 640400,
			"py": "gy"
		}, {
			"name": "高雄市",
			"city_pinyin": "gaoxiong",
			"city_id": 710500,
			"py": "gx"
		}, {
			"name": "甘孜藏族自治州",
			"city_pinyin": "ganzizangzuzizhizhou",
			"city_id": 513300,
			"py": "gzzzzzz"
		}, {
			"name": "甘南藏族自治州",
			"city_pinyin": "gannanzangzuzizhizhou",
			"city_id": 623000,
			"py": "gnzzzzz"
		}, {
			"name": "盖州市",
			"city_pinyin": "gaizhoushi",
			"city_id": 210881,
			"py": "gzs"
		}, {
			"name": "巩义市",
			"city_pinyin": "gongyishi",
			"city_id": 410181,
			"py": "gys"
		}, {
			"name": "公主岭市",
			"city_pinyin": "gongzhulingshi",
			"city_id": 220381,
			"py": "gzls"
		}, {
			"name": "广汉市",
			"city_pinyin": "guanghanshi",
			"city_id": 510681,
			"py": "ghs"
		}, ]
	}, {
		"letter": "H",
		"data": [{
			"name": "哈尔滨市",
			"city_pinyin": "haerbin",
			"city_id": 230100,
			"py": "heb"
		}, {
			"name": "海口市",
			"city_pinyin": "haikou",
			"city_id": 460100,
			"py": "hk"
		}, {
			"name": "海南藏族自治州",
			"city_pinyin": "hainanzangzuzizhizhou",
			"city_id": 632500,
			"py": "hnzzzzz"
		}, {
			"name": "海宁市",
			"city_pinyin": "hainingshi",
			"city_id": 330481,
			"py": "hns"
		}, {
			"name": "海西蒙古族藏族自治州",
			"city_pinyin": "haiximengguzuzangzuzizhizhou",
			"city_id": 632800,
			"py": "hxmgzzzzzz"
		}, {
			"name": "哈密市",
			"city_pinyin": "hamishi",
			"city_id": 652201,
			"py": "hms"
		}, {
			"name": "汉川市",
			"city_pinyin": "hanchuanshi",
			"city_id": 420984,
			"py": "hcs"
		}, {
			"name": "邯郸市",
			"city_pinyin": "handan",
			"city_id": 130400,
			"py": "hd"
		}, {
			"name": "杭州市",
			"city_pinyin": "hangzhou",
			"city_id": 330100,
			"py": "hz"
		}, {
			"name": "汉中市",
			"city_pinyin": "hanzhong",
			"city_id": 610700,
			"py": "hz"
		}, {
			"name": "鹤壁市",
			"city_pinyin": "hebi",
			"city_id": 410600,
			"py": "hb"
		}, {
			"name": "河池市",
			"city_pinyin": "hechi",
			"city_id": 451200,
			"py": "hc"
		}, {
			"name": "合肥市",
			"city_pinyin": "hefei",
			"city_id": 340100,
			"py": "hf"
		}, {
			"name": "鹤岗市",
			"city_pinyin": "hegang",
			"city_id": 230400,
			"py": "hg"
		}, {
			"name": "黑河市",
			"city_pinyin": "heihe",
			"city_id": 231100,
			"py": "hh"
		}, {
			"name": "河间市",
			"city_pinyin": "hejianshi",
			"city_id": 130984,
			"py": "hjs"
		}, {
			"name": "河津市",
			"city_pinyin": "hejinshi",
			"city_id": 140882,
			"py": "hjs"
		}, {
			"name": "衡阳市",
			"city_pinyin": "hengyang",
			"city_id": 430400,
			"py": "hy"
		}, {
			"name": "鹤山市",
			"city_pinyin": "heshanshi",
			"city_id": 440784,
			"py": "hss"
		}, {
			"name": "合山市",
			"city_pinyin": "heshanshi",
			"city_id": 451381,
			"py": "hss"
		}, {
			"name": "河源市",
			"city_pinyin": "heyuan",
			"city_id": 441600,
			"py": "hy"
		}, {
			"name": "菏泽市",
			"city_pinyin": "heze",
			"city_id": 371700,
			"py": "hz"
		}, {
			"name": "贺州市",
			"city_pinyin": "hezhou",
			"city_id": 451100,
			"py": "hz"
		}, {
			"name": "合作市",
			"city_pinyin": "hezuoshi",
			"city_id": 623001,
			"py": "hzs"
		}, {
			"name": "洪湖市",
			"city_pinyin": "honghushi",
			"city_id": 421083,
			"py": "hhs"
		}, {
			"name": "洪江市",
			"city_pinyin": "hongjiangshi",
			"city_id": 431281,
			"py": "hjs"
		}, {
			"name": "桦甸市",
			"city_pinyin": "huadianshi",
			"city_id": 220282,
			"py": "hds"
		}, {
			"name": "淮安市",
			"city_pinyin": "huaian",
			"city_id": 320800,
			"py": "ha"
		}, {
			"name": "淮北市",
			"city_pinyin": "huaibei",
			"city_id": 340600,
			"py": "hb"
		}, {
			"name": "怀化市",
			"city_pinyin": "huaihua",
			"city_id": 431200,
			"py": "hh"
		}, {
			"name": "淮南市",
			"city_pinyin": "huainan",
			"city_id": 340400,
			"py": "hn"
		}, {
			"name": "黄冈市",
			"city_pinyin": "huanggang",
			"city_id": 421100,
			"py": "hg"
		}, {
			"name": "黄南藏族自治州",
			"city_pinyin": "huangnanzangzuzizhizhou",
			"city_id": 632300,
			"py": "hnzzzzz"
		}, {
			"name": "黄山市",
			"city_pinyin": "huangshan",
			"city_id": 341000,
			"py": "hs"
		}, {
			"name": "黄石市",
			"city_pinyin": "huangshi",
			"city_id": 420200,
			"py": "hs"
		}, {
			"name": "呼和浩特市",
			"city_pinyin": "huhehaote",
			"city_id": 150100,
			"py": "hhht"
		}, {
			"name": "惠州市",
			"city_pinyin": "huizhou",
			"city_id": 441300,
			"py": "hz"
		}, {
			"name": "虎林市",
			"city_pinyin": "hulinshi",
			"city_id": 230381,
			"py": "hls"
		}, {
			"name": "葫芦岛市",
			"city_pinyin": "huludao",
			"city_id": 211400,
			"py": "hld"
		}, {
			"name": "呼伦贝尔市",
			"city_pinyin": "hulunbeier",
			"city_id": 150700,
			"py": "hlbe"
		}, {
			"name": "珲春市",
			"city_pinyin": "hunchunshi",
			"city_id": 222404,
			"py": "hcs"
		}, {
			"name": "湖州市",
			"city_pinyin": "huzhou",
			"city_id": 330500,
			"py": "hz"
		}, ]
	}, {
		"letter": "J",
		"data": [{
			"name": "嘉禾",
			"city_pinyin": "jiahe",
			"city_id": 431024,
			"py": "jh"
		}, {
			"name": "夹江",
			"city_pinyin": "jiajiang",
			"city_id": 511126,
			"py": "jj"
		}, {
			"name": "佳木斯",
			"city_pinyin": "jiamusi",
			"city_id": 230800,
			"py": "jms"
		}, {
			"name": "吉安",
			"city_pinyin": "jian",
			"city_id": 360800,
			"py": "ja"
		}, {
			"name": "集安",
			"city_pinyin": "jian",
			"city_id": 220582,
			"py": "ja"
		}, {
			"name": "建昌",
			"city_pinyin": "jianchang",
			"city_id": 211422,
			"py": "jc"
		}, {
			"name": "建德市",
			"city_pinyin": "jiandeshi",
			"city_id": 330182,
			"py": "jds"
		}, {
			"name": "江安",
			"city_pinyin": "jiangan",
			"city_id": 511523,
			"py": "ja"
		}, {
			"name": "江都市",
			"city_pinyin": "jiangdushi",
			"city_id": 321012,
			"py": "jds"
		}, {
			"name": "剑阁",
			"city_pinyin": "jiange",
			"city_id": 510823,
			"py": "jg"
		}, {
			"name": "江门",
			"city_pinyin": "jiangmen",
			"city_id": 440700,
			"py": "jm"
		}, {
			"name": "江山市",
			"city_pinyin": "jiangshanshi",
			"city_id": 330881,
			"py": "jss"
		}, {
			"name": "姜堰市",
			"city_pinyin": "jiangyanshi",
			"city_id": 321284,
			"py": "jys"
		}, {
			"name": "江阴",
			"city_pinyin": "jiangyin",
			"city_id": 320281,
			"py": "jy"
		}, {
			"name": "江油市",
			"city_pinyin": "jiangyoushi",
			"city_id": 510781,
			"py": "jys"
		}, {
			"name": "建瓯市",
			"city_pinyin": "jianoushi",
			"city_id": 350783,
			"py": "jos"
		}, {
			"name": "建平",
			"city_pinyin": "jianping",
			"city_id": 211322,
			"py": "jp"
		}, {
			"name": "建始",
			"city_pinyin": "jianshi",
			"city_id": 422822,
			"py": "js"
		}, {
			"name": "犍为",
			"city_pinyin": "jianwei",
			"city_id": 511123,
			"py": "qw"
		}, {
			"name": "简阳市",
			"city_pinyin": "jianyangshi",
			"city_id": 512081,
			"py": "jys"
		}, {
			"name": "建阳市",
			"city_pinyin": "jianyangshi",
			"city_id": 350784,
			"py": "jys"
		}, {
			"name": "交城",
			"city_pinyin": "jiaocheng",
			"city_id": 141122,
			"py": "jc"
		}, {
			"name": "蛟河市",
			"city_pinyin": "jiaoheshi",
			"city_id": 220281,
			"py": "jhs"
		}, {
			"name": "胶南市",
			"city_pinyin": "jiaonanshi",
			"city_id": 370284,
			"py": "jns"
		}, {
			"name": "胶州市",
			"city_pinyin": "jiaozhoushi",
			"city_id": 370281,
			"py": "jzs"
		}, {
			"name": "焦作",
			"city_pinyin": "jiaozuo",
			"city_id": 410800,
			"py": "jz"
		}, {
			"name": "嘉兴",
			"city_pinyin": "jiaxing",
			"city_id": 330400,
			"py": "jx"
		}, {
			"name": "嘉义",
			"city_pinyin": "jiayi",
			"city_id": 712000,
			"py": "jy"
		}, {
			"name": "嘉鱼",
			"city_pinyin": "jiayu",
			"city_id": 421221,
			"py": "jy"
		}, {
			"name": "嘉峪关",
			"city_pinyin": "jiayuguan",
			"city_id": 620200,
			"py": "jyg"
		}, {
			"name": "鸡东",
			"city_pinyin": "jidong",
			"city_id": 230321,
			"py": "jd"
		}, {
			"name": "界首市",
			"city_pinyin": "jieshoushi",
			"city_id": 341282,
			"py": "jss"
		}, {
			"name": "介休市",
			"city_pinyin": "jiexiushi",
			"city_id": 140781,
			"py": "jxs"
		}, {
			"name": "揭阳",
			"city_pinyin": "jieyang",
			"city_id": 445200,
			"py": "jy"
		}, {
			"name": "吉利",
			"city_pinyin": "jili",
			"city_id": 410306,
			"py": "jl"
		}, {
			"name": "吉林",
			"city_pinyin": "jilin",
			"city_id": 220200,
			"py": "jl"
		}, {
			"name": "基隆",
			"city_pinyin": "jilong",
			"city_id": 711600,
			"py": "jl"
		}, {
			"name": "济南",
			"city_pinyin": "jinan",
			"city_id": 370100,
			"py": "jn"
		}, {
			"name": "金昌",
			"city_pinyin": "jinchang",
			"city_id": 620300,
			"py": "jc"
		}, {
			"name": "晋城",
			"city_pinyin": "jincheng",
			"city_id": 140500,
			"py": "jc"
		}, {
			"name": "景德镇",
			"city_pinyin": "jingdezhen",
			"city_id": 360200,
			"py": "jdz"
		}, {
			"name": "井冈山市",
			"city_pinyin": "jinggangshanshi",
			"city_id": 360881,
			"py": "jgss"
		}, {
			"name": "景洪市",
			"city_pinyin": "jinghongshi",
			"city_id": 532801,
			"py": "jhs"
		}, {
			"name": "靖江市",
			"city_pinyin": "jingjiangshi",
			"city_id": 321282,
			"py": "jjs"
		}, {
			"name": "荆门",
			"city_pinyin": "jingmen",
			"city_id": 420800,
			"py": "jm"
		}, {
			"name": "景泰",
			"city_pinyin": "jingtai",
			"city_id": 620423,
			"py": "jt"
		}, {
			"name": "泾阳",
			"city_pinyin": "jingyang",
			"city_id": 610423,
			"py": "jy"
		}, {
			"name": "靖宇",
			"city_pinyin": "jingyu",
			"city_id": 220622,
			"py": "jy"
		}, {
			"name": "荆州",
			"city_pinyin": "jingzhou",
			"city_id": 421000,
			"py": "jz"
		}, {
			"name": "金华",
			"city_pinyin": "jinhua",
			"city_id": 330700,
			"py": "jh"
		}, {
			"name": "济宁",
			"city_pinyin": "jining",
			"city_id": 370800,
			"py": "jn"
		}, {
			"name": "晋江",
			"city_pinyin": "jinjiang",
			"city_id": 350582,
			"py": "jj"
		}, {
			"name": "晋宁",
			"city_pinyin": "jinning",
			"city_id": 530122,
			"py": "jn"
		}, {
			"name": "津市市",
			"city_pinyin": "jinshishi",
			"city_id": 430781,
			"py": "jss"
		}, {
			"name": "金坛市",
			"city_pinyin": "jintanshi",
			"city_id": 320482,
			"py": "jts"
		}, {
			"name": "金寨",
			"city_pinyin": "jinzhai",
			"city_id": 341524,
			"py": "jz"
		}, {
			"name": "晋中",
			"city_pinyin": "jinzhong",
			"city_id": 140700,
			"py": "jz"
		}, {
			"name": "锦州",
			"city_pinyin": "jinzhou",
			"city_id": 210700,
			"py": "jz"
		}, {
			"name": "晋州",
			"city_pinyin": "jinzhou",
			"city_id": 130183,
			"py": "jz"
		}, {
			"name": "吉首",
			"city_pinyin": "jishou",
			"city_id": 433101,
			"py": "js"
		}, {
			"name": "九江",
			"city_pinyin": "jiujiang",
			"city_id": 360400,
			"py": "jj"
		}, {
			"name": "酒泉",
			"city_pinyin": "jiuquan",
			"city_id": 620900,
			"py": "jq"
		}, {
			"name": "九台市",
			"city_pinyin": "jiutaishi",
			"city_id": 220181,
			"py": "jts"
		}, {
			"name": "鸡西",
			"city_pinyin": "jixi",
			"city_id": 230300,
			"py": "jx"
		}, {
			"name": "济源",
			"city_pinyin": "jiyuan",
			"city_id": 419001,
			"py": "jy"
		}, {
			"name": "冀州",
			"city_pinyin": "jizhou",
			"city_id": 131181,
			"py": "jz"
		}, {
			"name": "巨鹿",
			"city_pinyin": "julu",
			"city_id": 130529,
			"py": "jl"
		}, {
			"name": "句容",
			"city_pinyin": "jurong",
			"city_id": 321183,
			"py": "jr"
		}, ]
	}, {
		"letter": "K",
		"data": [{
			"name": "开封",
			"city_pinyin": "kaifeng",
			"city_id": 410200,
			"py": "kf"
		}, {
			"name": "开化",
			"city_pinyin": "kaihua",
			"city_id": 330824,
			"py": "kh"
		}, {
			"name": "开江",
			"city_pinyin": "kaijiang",
			"city_id": 511723,
			"py": "kj"
		}, {
			"name": "凯里",
			"city_pinyin": "kaili",
			"city_id": 522601,
			"py": "kl"
		}, {
			"name": "开鲁",
			"city_pinyin": "kailu",
			"city_id": 150523,
			"py": "kl"
		}, {
			"name": "开平市",
			"city_pinyin": "kaipingshi",
			"city_id": 440783,
			"py": "kps"
		}, {
			"name": "开远市",
			"city_pinyin": "kaiyuanshi",
			"city_id": 532502,
			"py": "kys"
		}, {
			"name": "开原市",
			"city_pinyin": "kaiyuanshi",
			"city_id": 211282,
			"py": "kys"
		}, {
			"name": "康定",
			"city_pinyin": "kangding",
			"city_id": 513321,
			"py": "kd"
		}, {
			"name": "喀什市",
			"city_pinyin": "kashenshi",
			"city_id": 653101,
			"py": "kss"
		}, {
			"name": "喀什地区",
			"city_pinyin": "kashidiqu",
			"city_id": 653100,
			"py": "ksdq"
		}, {
			"name": "昆明",
			"city_pinyin": "kunming",
			"city_id": 530100,
			"py": "km"
		}, {
			"name": "昆山",
			"city_pinyin": "kunshan",
			"city_id": 320583,
			"py": "ks"
		}]
	}, {
		"letter": "L",
		"data": [{
			"name": "来宾",
			"city_pinyin": "laibin",
			"city_id": 451300,
			"py": "lb"
		}, {
			"name": "来凤",
			"city_pinyin": "laifeng",
			"city_id": 422827,
			"py": "lf"
		}, {
			"name": "涞水",
			"city_pinyin": "laishui",
			"city_id": 130623,
			"py": "ls"
		}, {
			"name": "莱芜",
			"city_pinyin": "laiwu",
			"city_id": 371200,
			"py": "lw"
		}, {
			"name": "莱西市",
			"city_pinyin": "laixishi",
			"city_id": 370285,
			"py": "lxs"
		}, {
			"name": "莱阳市",
			"city_pinyin": "laiyangshi",
			"city_id": 370682,
			"py": "lys"
		}, {
			"name": "莱州市",
			"city_pinyin": "laizhoushi",
			"city_id": 370683,
			"py": "lzs"
		}, {
			"name": "廊坊",
			"city_pinyin": "langfang",
			"city_id": 131000,
			"py": "lf"
		}, {
			"name": "郎溪",
			"city_pinyin": "langxi",
			"city_id": 341821,
			"py": "lx"
		}, {
			"name": "阆中市",
			"city_pinyin": "langzhongshi",
			"city_id": 511381,
			"py": "lzs"
		}, {
			"name": "兰西",
			"city_pinyin": "lanxi",
			"city_id": 231222,
			"py": "lx"
		}, {
			"name": "兰溪市",
			"city_pinyin": "lanxishi",
			"city_id": 330781,
			"py": "lxs"
		}, {
			"name": "兰州",
			"city_pinyin": "lanzhou",
			"city_id": 620100,
			"py": "lz"
		}, {
			"name": "老河口市",
			"city_pinyin": "laohekoushi",
			"city_id": 420682,
			"py": "lhks"
		}, {
			"name": "拉萨",
			"city_pinyin": "lasa",
			"city_id": 540100,
			"py": "ls"
		}, {
			"name": "乐昌",
			"city_pinyin": "lechang",
			"city_id": 440281,
			"py": "lc"
		}, {
			"name": "耒阳市",
			"city_pinyin": "leiyangshi",
			"city_id": 430481,
			"py": "lys"
		}, {
			"name": "雷州市",
			"city_pinyin": "leizhoushi",
			"city_id": 440882,
			"py": "lzs"
		}, {
			"name": "乐陵市",
			"city_pinyin": "lelingshi",
			"city_id": 371481,
			"py": "lls"
		}, {
			"name": "冷水江市",
			"city_pinyin": "lengshuijiangshi",
			"city_id": 431381,
			"py": "lsjs"
		}, {
			"name": "乐平市",
			"city_pinyin": "lepingshi",
			"city_id": 360281,
			"py": "lps"
		}, {
			"name": "乐山",
			"city_pinyin": "leshan",
			"city_id": 511100,
			"py": "ls"
		}, {
			"name": "乐至",
			"city_pinyin": "lezhi",
			"city_id": 512022,
			"py": "lz"
		}, {
			"name": "连城",
			"city_pinyin": "liancheng",
			"city_id": 350825,
			"py": "lc"
		}, {
			"name": "凉山彝族自治州",
			"city_pinyin": "liangshanyizuzizhizhou",
			"city_id": 513400,
			"py": "lsyzzzz"
		}, {
			"name": "廉江市",
			"city_pinyin": "lianjiangshi",
			"city_id": 440881,
			"py": "ljs"
		}, {
			"name": "涟源市",
			"city_pinyin": "lianyuanshi",
			"city_id": 431382,
			"py": "lys"
		}, {
			"name": "连云港",
			"city_pinyin": "lianyungang",
			"city_id": 320700,
			"py": "lyg"
		}, {
			"name": "连州",
			"city_pinyin": "lianzhou",
			"city_id": 441882,
			"py": "lz"
		}, {
			"name": "聊城",
			"city_pinyin": "liaocheng",
			"city_id": 371500,
			"py": "lc"
		}, {
			"name": "辽阳",
			"city_pinyin": "liaoyang",
			"city_id": 211000,
			"py": "ly"
		}, {
			"name": "利川市",
			"city_pinyin": "lichuanshi",
			"city_id": 422802,
			"py": "lcs"
		}, {
			"name": "丽江",
			"city_pinyin": "lijiang",
			"city_id": 530700,
			"py": "lj"
		}, {
			"name": "醴陵市",
			"city_pinyin": "lilingshi",
			"city_id": 430281,
			"py": "lls"
		}, {
			"name": "临安",
			"city_pinyin": "linan",
			"city_id": 330185,
			"py": "la"
		}, {
			"name": "临沧",
			"city_pinyin": "lincang",
			"city_id": 530900,
			"py": "lc"
		}, {
			"name": "临汾",
			"city_pinyin": "linfen",
			"city_id": 141000,
			"py": "lf"
		}, {
			"name": "灵宝市",
			"city_pinyin": "lingbaoshi",
			"city_id": 411282,
			"py": "lbs"
		}, {
			"name": "灵川",
			"city_pinyin": "lingchuan",
			"city_id": 450323,
			"py": "lc"
		}, {
			"name": "凌海",
			"city_pinyin": "linghai",
			"city_id": 210781,
			"py": "lh"
		}, {
			"name": "灵武",
			"city_pinyin": "lingwu",
			"city_id": 640181,
			"py": "lw"
		}, {
			"name": "凌源市",
			"city_pinyin": "lingyuanshi",
			"city_id": 211382,
			"py": "lys"
		}, {
			"name": "临海市",
			"city_pinyin": "linhaishi",
			"city_id": 331082,
			"py": "lhs"
		}, {
			"name": "临江",
			"city_pinyin": "linjiang",
			"city_id": 220681,
			"py": "lj"
		}, {
			"name": "临清市",
			"city_pinyin": "linqingshi",
			"city_id": 371581,
			"py": "lqs"
		}, {
			"name": "临夏回族自治州",
			"city_pinyin": "linxiahuizuzizhizhou",
			"city_id": 622900,
			"py": "lxhzzzz"
		}, {
			"name": "临湘市",
			"city_pinyin": "linxiangshi",
			"city_id": 430682,
			"py": "lxs"
		}, {
			"name": "临夏市",
			"city_pinyin": "linxiashi",
			"city_id": 622901,
			"py": "lxs"
		}, {
			"name": "临沂",
			"city_pinyin": "linyi",
			"city_id": 371300,
			"py": "ly"
		}, {
			"name": "林州市",
			"city_pinyin": "linzhoushi",
			"city_id": 410581,
			"py": "lzs"
		}, {
			"name": "丽水",
			"city_pinyin": "lishui",
			"city_id": 331100,
			"py": "ls"
		}, {
			"name": "柳河",
			"city_pinyin": "liuhe",
			"city_id": 220524,
			"py": "lh"
		}, {
			"name": "柳林",
			"city_pinyin": "liulin",
			"city_id": 141125,
			"py": "ll"
		}, {
			"name": "六盘水",
			"city_pinyin": "liupanshui",
			"city_id": 520200,
			"py": "lps"
		}, {
			"name": "浏阳市",
			"city_pinyin": "liuyangshi",
			"city_id": 430181,
			"py": "lys"
		}, {
			"name": "柳州",
			"city_pinyin": "liuzhou",
			"city_id": 450200,
			"py": "lz"
		}, {
			"name": "溧阳市",
			"city_pinyin": "liyangshi",
			"city_id": 320481,
			"py": "lys"
		}, {
			"name": "龙港市",
			"city_pinyin": "longgangshi",
			"city_id": 10000024,
			"py": "lgs"
		}, {
			"name": "龙海市",
			"city_pinyin": "longhaishi",
			"city_id": 350681,
			"py": "lhs"
		}, {
			"name": "隆化",
			"city_pinyin": "longhua",
			"city_id": 130825,
			"py": "lh"
		}, {
			"name": "龙井市",
			"city_pinyin": "longjingshi",
			"city_id": 222405,
			"py": "ljs"
		}, {
			"name": "龙口市",
			"city_pinyin": "longkoushi",
			"city_id": 370681,
			"py": "lks"
		}, {
			"name": "陇南",
			"city_pinyin": "longnan",
			"city_id": 621200,
			"py": "ln"
		}, {
			"name": "龙泉市",
			"city_pinyin": "longquanshi",
			"city_id": 331181,
			"py": "lqs"
		}, {
			"name": "龙岩",
			"city_pinyin": "longyan",
			"city_id": 350800,
			"py": "ly"
		}, {
			"name": "娄底",
			"city_pinyin": "loudi",
			"city_id": 431300,
			"py": "ld"
		}, {
			"name": "六安",
			"city_pinyin": "luan",
			"city_id": 341500,
			"py": "la"
		}, {
			"name": "栾城",
			"city_pinyin": "luancheng",
			"city_id": 130124,
			"py": "lc"
		}, {
			"name": "栾川",
			"city_pinyin": "luanchuan",
			"city_id": 410324,
			"py": "lc"
		}, {
			"name": "陆丰市",
			"city_pinyin": "lufengshi",
			"city_id": 441581,
			"py": "lfs"
		}, {
			"name": "罗定",
			"city_pinyin": "luoding",
			"city_id": 445381,
			"py": "ld"
		}, {
			"name": "漯河",
			"city_pinyin": "luohe",
			"city_id": 411100,
			"py": "th"
		}, {
			"name": "罗江",
			"city_pinyin": "luojiang",
			"city_id": 510626,
			"py": "lj"
		}, {
			"name": "洛阳",
			"city_pinyin": "luoyang",
			"city_id": 410300,
			"py": "ly"
		}, {
			"name": "罗源",
			"city_pinyin": "luoyuan",
			"city_id": 350123,
			"py": "ly"
		}, {
			"name": "鹿泉",
			"city_pinyin": "luquan",
			"city_id": 130185,
			"py": "lq"
		}, {
			"name": "卢氏",
			"city_pinyin": "lushi",
			"city_id": 411224,
			"py": "ls"
		}, {
			"name": "泸州",
			"city_pinyin": "luzhou",
			"city_id": 510500,
			"py": "lz"
		}, {
			"name": "吕梁",
			"city_pinyin": "lvliang",
			"city_id": 141100,
			"py": "ll"
		}]
	}, {
		"letter": "M",
		"data": [{
			"name": "马鞍山",
			"city_pinyin": "maanshan",
			"city_id": 340500,
			"py": "mas"
		}, {
			"name": "麻城市",
			"city_pinyin": "machengshi",
			"city_id": 421181,
			"py": "mcs"
		}, {
			"name": "马尔康",
			"city_pinyin": "maerkang",
			"city_id": 513229,
			"py": "mek"
		}, {
			"name": "满城",
			"city_pinyin": "mancheng",
			"city_id": 130621,
			"py": "mc"
		}, {
			"name": "芒市",
			"city_pinyin": "mangshi",
			"city_id": 533103,
			"py": "ms"
		}, {
			"name": "茫崖市",
			"city_pinyin": "mangyashi",
			"city_id": 10000022,
			"py": "mys"
		}, {
			"name": "满洲里市",
			"city_pinyin": "manzhoulishi",
			"city_id": 150781,
			"py": "mzls"
		}, {
			"name": "茂名",
			"city_pinyin": "maoming",
			"city_id": 440900,
			"py": "mm"
		}, {
			"name": "麻涌",
			"city_pinyin": "mayong",
			"city_id": 4419026,
			"py": "my"
		}, {
			"name": "梅河口市",
			"city_pinyin": "meihekoushi",
			"city_id": 220581,
			"py": "mhks"
		}, {
			"name": "眉山",
			"city_pinyin": "meishan",
			"city_id": 511400,
			"py": "ms"
		}, {
			"name": "湄潭",
			"city_pinyin": "meitan",
			"city_id": 520328,
			"py": "mt"
		}, {
			"name": "梅州",
			"city_pinyin": "meizhou",
			"city_id": 441400,
			"py": "mz"
		}, {
			"name": "孟津",
			"city_pinyin": "mengjin",
			"city_id": 410322,
			"py": "mj"
		}, {
			"name": "孟州",
			"city_pinyin": "mengzhou",
			"city_id": 410883,
			"py": "mz"
		}, {
			"name": "蒙自",
			"city_pinyin": "mengzi",
			"city_id": 532503,
			"py": "mz"
		}, {
			"name": "渑池",
			"city_pinyin": "mianchi",
			"city_id": 411221,
			"py": "mc"
		}, {
			"name": "绵阳",
			"city_pinyin": "mianyang",
			"city_id": 510700,
			"py": "my"
		}, {
			"name": "绵竹市",
			"city_pinyin": "mianzhushi",
			"city_id": 510683,
			"py": "mzs"
		}, {
			"name": "汨罗市",
			"city_pinyin": "miluoshi",
			"city_id": 430681,
			"py": "mls"
		}, {
			"name": "明光市",
			"city_pinyin": "mingguangshi",
			"city_id": 341182,
			"py": "mgs"
		}, {
			"name": "闽清",
			"city_pinyin": "minqing",
			"city_id": 350124,
			"py": "mq"
		}, {
			"name": "密山",
			"city_pinyin": "mishan",
			"city_id": 230382,
			"py": "ms"
		}, {
			"name": "米易",
			"city_pinyin": "miyi",
			"city_id": 510421,
			"py": "my"
		}, {
			"name": "牡丹江",
			"city_pinyin": "mudanjiang",
			"city_id": 231000,
			"py": "mdj"
		}, {
			"name": "穆棱市",
			"city_pinyin": "mulengshi",
			"city_id": 231085,
			"py": "mls"
		}]
	}, {
		"letter": "N",
		"data": [{
			"name": "南安市",
			"city_pinyin": "nananshi",
			"city_id": 350583,
			"py": "nas"
		}, {
			"name": "南昌",
			"city_pinyin": "nanchang",
			"city_id": 360100,
			"py": "nc"
		}, {
			"name": "南充",
			"city_pinyin": "nanchong",
			"city_id": 511300,
			"py": "nc"
		}, {
			"name": "南川",
			"city_pinyin": "nanchuan",
			"city_id": 500119,
			"py": "nc"
		}, {
			"name": "南丰",
			"city_pinyin": "nanfeng",
			"city_id": 361023,
			"py": "nf"
		}, {
			"name": "南宫市",
			"city_pinyin": "nangongshi",
			"city_id": 130581,
			"py": "ngs"
		}, {
			"name": "南江",
			"city_pinyin": "nanjiang",
			"city_id": 511922,
			"py": "nj"
		}, {
			"name": "南京",
			"city_pinyin": "nanjing",
			"city_id": 320100,
			"py": "nj"
		}, {
			"name": "南靖",
			"city_pinyin": "nanjing",
			"city_id": 350627,
			"py": "nj"
		}, {
			"name": "南极洲",
			"city_pinyin": "nanjizhou",
			"city_id": 999999,
			"py": "njz"
		}, {
			"name": "南康市",
			"city_pinyin": "nankangshi",
			"city_id": 360782,
			"py": "nks"
		}, {
			"name": "南乐",
			"city_pinyin": "nanle",
			"city_id": 410923,
			"py": "nl"
		}, {
			"name": "南陵",
			"city_pinyin": "nanling",
			"city_id": 340223,
			"py": "nl"
		}, {
			"name": "南宁",
			"city_pinyin": "nanning",
			"city_id": 450100,
			"py": "nn"
		}, {
			"name": "南平",
			"city_pinyin": "nanping",
			"city_id": 350700,
			"py": "np"
		}, {
			"name": "南通",
			"city_pinyin": "nantong",
			"city_id": 320600,
			"py": "nt"
		}, {
			"name": "南溪",
			"city_pinyin": "nanxi",
			"city_id": 511503,
			"py": "nx"
		}, {
			"name": "南雄",
			"city_pinyin": "nanxiong",
			"city_id": 440282,
			"py": "nx"
		}, {
			"name": "南阳",
			"city_pinyin": "nanyang",
			"city_id": 411300,
			"py": "ny"
		}, {
			"name": "南岳",
			"city_pinyin": "nanyue",
			"city_id": 430412,
			"py": "ny"
		}, {
			"name": "南郑",
			"city_pinyin": "nanzheng",
			"city_id": 610721,
			"py": "nz"
		}, {
			"name": "讷河市",
			"city_pinyin": "neheshi",
			"city_id": 230281,
			"py": "nhs"
		}, {
			"name": "内黄",
			"city_pinyin": "neihuang",
			"city_id": 410527,
			"py": "nh"
		}, {
			"name": "内江",
			"city_pinyin": "neijiang",
			"city_id": 511000,
			"py": "nj"
		}, {
			"name": "宁安市",
			"city_pinyin": "ninganshi",
			"city_id": 231084,
			"py": "nas"
		}, {
			"name": "宁波",
			"city_pinyin": "ningbo",
			"city_id": 330200,
			"py": "nb"
		}, {
			"name": "宁城",
			"city_pinyin": "ningcheng",
			"city_id": 150429,
			"py": "nc"
		}, {
			"name": "宁德",
			"city_pinyin": "ningde",
			"city_id": 350900,
			"py": "nd"
		}, {
			"name": "宁国市",
			"city_pinyin": "ningguoshi",
			"city_id": 341881,
			"py": "ngs"
		}, {
			"name": "宁津",
			"city_pinyin": "ningjin",
			"city_id": 371422,
			"py": "nj"
		}, {
			"name": "宁陵",
			"city_pinyin": "ningling",
			"city_id": 411423,
			"py": "nl"
		}, {
			"name": "怒江傈僳族自治州",
			"city_pinyin": "nujianglisuzuzizhizhou",
			"city_id": 533300,
			"py": "njlszzzz"
		}]
	}, {
		"letter": "P",
		"data": [{
			"name": "磐安",
			"city_pinyin": "panan",
			"city_id": 330727,
			"py": "pa"
		}, {
			"name": "盘锦",
			"city_pinyin": "panjin",
			"city_id": 211100,
			"py": "pj"
		}, {
			"name": "磐石市",
			"city_pinyin": "panshishi",
			"city_id": 220284,
			"py": "pss"
		}, {
			"name": "攀枝花",
			"city_pinyin": "panzhihua",
			"city_id": 510400,
			"py": "pzh"
		}, {
			"name": "蓬莱",
			"city_pinyin": "penglai",
			"city_id": 370684,
			"py": "pl"
		}, {
			"name": "彭山",
			"city_pinyin": "pengshan",
			"city_id": 511422,
			"py": "ps"
		}, {
			"name": "蓬溪",
			"city_pinyin": "pengxi",
			"city_id": 510921,
			"py": "px"
		}, {
			"name": "彭泽",
			"city_pinyin": "pengze",
			"city_id": 360430,
			"py": "pz"
		}, {
			"name": "彭州市",
			"city_pinyin": "pengzhoushi",
			"city_id": 510182,
			"py": "pzs"
		}, {
			"name": "平顶山",
			"city_pinyin": "pingdingshan",
			"city_id": 410400,
			"py": "pds"
		}, {
			"name": "平度市",
			"city_pinyin": "pingdushi",
			"city_id": 370283,
			"py": "pds"
		}, {
			"name": "平谷",
			"city_pinyin": "pinggu",
			"city_id": 110117,
			"py": "pg"
		}, {
			"name": "平湖市",
			"city_pinyin": "pinghushi",
			"city_id": 330482,
			"py": "phs"
		}, {
			"name": "平凉",
			"city_pinyin": "pingliang",
			"city_id": 620800,
			"py": "pl"
		}, {
			"name": "平陆",
			"city_pinyin": "pinglu",
			"city_id": 140829,
			"py": "pl"
		}, {
			"name": "平罗",
			"city_pinyin": "pingluo",
			"city_id": 640221,
			"py": "pl"
		}, {
			"name": "平泉",
			"city_pinyin": "pingquan",
			"city_id": 130823,
			"py": "pq"
		}, {
			"name": "平山",
			"city_pinyin": "pingshan",
			"city_id": 130131,
			"py": "ps"
		}, {
			"name": "平潭",
			"city_pinyin": "pingtan",
			"city_id": 350128,
			"py": "pt"
		}, {
			"name": "萍乡",
			"city_pinyin": "pingxiang",
			"city_id": 360300,
			"py": "px"
		}, {
			"name": "平乡",
			"city_pinyin": "pingxiang",
			"city_id": 130532,
			"py": "px"
		}, {
			"name": "凭祥市",
			"city_pinyin": "pingxiangshi",
			"city_id": 451481,
			"py": "pxs"
		}, {
			"name": "邳州市",
			"city_pinyin": "pizhoushi",
			"city_id": 320382,
			"py": "pzs"
		}, {
			"name": "蒲城",
			"city_pinyin": "pucheng",
			"city_id": 610526,
			"py": "pc"
		}, {
			"name": "普洱",
			"city_pinyin": "puer",
			"city_id": 530800,
			"py": "pe"
		}, {
			"name": "蒲江",
			"city_pinyin": "pujiang",
			"city_id": 510131,
			"py": "pj"
		}, {
			"name": "普兰店市",
			"city_pinyin": "pulandianshi",
			"city_id": 210282,
			"py": "plds"
		}, {
			"name": "普宁市",
			"city_pinyin": "puningshi",
			"city_id": 445281,
			"py": "pns"
		}, {
			"name": "莆田",
			"city_pinyin": "putian",
			"city_id": 350300,
			"py": "pt"
		}, {
			"name": "濮阳",
			"city_pinyin": "puyang",
			"city_id": 410900,
			"py": "py"
		}, ]
	}, {
		"letter": "Q",
		"data": [{
			"name": "乾安",
			"city_pinyin": "qianan",
			"city_id": 220723,
			"py": "qa"
		}, {
			"name": "迁安市",
			"city_pinyin": "qiananshi",
			"city_id": 130283,
			"py": "qas"
		}, {
			"name": "黔东南苗族侗族自治州",
			"city_pinyin": "qiandongnanmiaozudongzuzizhizhou",
			"city_id": 522600,
			"py": "qdnmzdzzzz"
		}, {
			"name": "潜江",
			"city_pinyin": "qianjiang",
			"city_id": 4290051,
			"py": "qj"
		}, {
			"name": "黔江",
			"city_pinyin": "qianjiang",
			"city_id": 500114,
			"py": "qj"
		}, {
			"name": "潜江市",
			"city_pinyin": "qianjiangshi",
			"city_id": 429005,
			"py": "qjs"
		}, {
			"name": "黔南布依族苗族自治州",
			"city_pinyin": "qiannanbuyizumiaozuzizhizhou",
			"city_id": 522700,
			"py": "qnbyzmzzzz"
		}, {
			"name": "迁西",
			"city_pinyin": "qianxi",
			"city_id": 130227,
			"py": "qx"
		}, {
			"name": "黔西南布依族苗族自治州",
			"city_pinyin": "qianxinanbuyizumiaozuzizhizhou",
			"city_id": 522300,
			"py": "qxnbyzmzzzz"
		}, {
			"name": "启东市",
			"city_pinyin": "qidongshi",
			"city_id": 320681,
			"py": "qds"
		}, {
			"name": "庆安",
			"city_pinyin": "qingan",
			"city_id": 231224,
			"py": "qa"
		}, {
			"name": "青川",
			"city_pinyin": "qingchuan",
			"city_id": 510822,
			"py": "qc"
		}, {
			"name": "青岛",
			"city_pinyin": "qingdao",
			"city_id": 370200,
			"py": "qd"
		}, {
			"name": "清丰",
			"city_pinyin": "qingfeng",
			"city_id": 410922,
			"py": "qf"
		}, {
			"name": "青神",
			"city_pinyin": "qingshen",
			"city_id": 511425,
			"py": "qs"
		}, {
			"name": "青铜峡市",
			"city_pinyin": "qingtongxiashi",
			"city_id": 640381,
			"py": "qtxs"
		}, {
			"name": "庆阳",
			"city_pinyin": "qingyang",
			"city_id": 621000,
			"py": "qy"
		}, {
			"name": "青阳",
			"city_pinyin": "qingyang",
			"city_id": 341723,
			"py": "qy"
		}, {
			"name": "清远",
			"city_pinyin": "qingyuan",
			"city_id": 441800,
			"py": "qy"
		}, {
			"name": "庆元",
			"city_pinyin": "qingyuan",
			"city_id": 331126,
			"py": "qy"
		}, {
			"name": "清镇市",
			"city_pinyin": "qingzhenshi",
			"city_id": 520181,
			"py": "qzs"
		}, {
			"name": "青州市",
			"city_pinyin": "qingzhoushi",
			"city_id": 370781,
			"py": "qzs"
		}, {
			"name": "秦皇岛",
			"city_pinyin": "qinhuangdao",
			"city_id": 130300,
			"py": "qhd"
		}, {
			"name": "沁阳市",
			"city_pinyin": "qinyangshi",
			"city_id": 410882,
			"py": "qys"
		}, {
			"name": "钦州",
			"city_pinyin": "qinzhou",
			"city_id": 450700,
			"py": "qz"
		}, {
			"name": "琼海",
			"city_pinyin": "qionghai",
			"city_id": 469002,
			"py": "qh"
		}, {
			"name": "邛崃市",
			"city_pinyin": "qionglaishi",
			"city_id": 510183,
			"py": "qls"
		}, {
			"name": "齐齐哈尔",
			"city_pinyin": "qiqihaer",
			"city_id": 230200,
			"py": "qqhe"
		}, {
			"name": "七台河",
			"city_pinyin": "qitaihe",
			"city_id": 230900,
			"py": "qth"
		}, {
			"name": "栖霞市",
			"city_pinyin": "qixiashi",
			"city_id": 370686,
			"py": "xxs"
		}, {
			"name": "泉州",
			"city_pinyin": "quanzhou",
			"city_id": 350500,
			"py": "qz"
		}, {
			"name": "曲阜市",
			"city_pinyin": "qufushi",
			"city_id": 370881,
			"py": "qfs"
		}, {
			"name": "曲江",
			"city_pinyin": "qujiang",
			"city_id": 440205,
			"py": "qj"
		}, {
			"name": "曲靖",
			"city_pinyin": "qujing",
			"city_id": 530300,
			"py": "qj"
		}, {
			"name": "衢州",
			"city_pinyin": "quzhou",
			"city_id": 330800,
			"py": "qz"
		}, {
			"name": "曲周",
			"city_pinyin": "quzhou",
			"city_id": 130435,
			"py": "qz"
		}]
	}, {
		"letter": "R",
		"data": [{
			"name": "仁化",
			"city_pinyin": "renhua",
			"city_id": 440224,
			"py": "rh"
		}, {
			"name": "仁怀市",
			"city_pinyin": "renhuaishi",
			"city_id": 520382,
			"py": "rhs"
		}, {
			"name": "任丘市",
			"city_pinyin": "renqiushi",
			"city_id": 130982,
			"py": "rqs"
		}, {
			"name": "日喀则",
			"city_pinyin": "rikaze",
			"city_id": 542300,
			"py": "rkz"
		}, {
			"name": "日照",
			"city_pinyin": "rizhao",
			"city_id": 371100,
			"py": "rz"
		}, {
			"name": "容城",
			"city_pinyin": "rongcheng",
			"city_id": 130629,
			"py": "rc"
		}, {
			"name": "荣成市",
			"city_pinyin": "rongchengshi",
			"city_id": 371082,
			"py": "rcs"
		}, {
			"name": "汝城",
			"city_pinyin": "rucheng",
			"city_id": 431026,
			"py": "rc"
		}, {
			"name": "如皋市",
			"city_pinyin": "rugaoshi",
			"city_id": 320682,
			"py": "rgs"
		}, {
			"name": "瑞昌",
			"city_pinyin": "ruichang",
			"city_id": 360481,
			"py": "rc"
		}, {
			"name": "瑞金市",
			"city_pinyin": "ruijinshi",
			"city_id": 360781,
			"py": "rjs"
		}, {
			"name": "瑞丽",
			"city_pinyin": "ruili",
			"city_id": 533102,
			"py": "rl"
		}, {
			"name": "乳山市",
			"city_pinyin": "rushanshi",
			"city_id": 371083,
			"py": "rss"
		}, {
			"name": "汝阳",
			"city_pinyin": "ruyang",
			"city_id": 410326,
			"py": "ry"
		}, {
			"name": "汝州",
			"city_pinyin": "ruzhou",
			"city_id": 410482,
			"py": "rz"
		}]
	}, {
		"letter": "S",
		"data": [{
			"name": "桑植",
			"city_pinyin": "sangzhi",
			"city_id": 430822,
			"py": "sz"
		}, {
			"name": "三河市",
			"city_pinyin": "sanheshi",
			"city_id": 131082,
			"py": "shs"
		}, {
			"name": "三门峡",
			"city_pinyin": "sanmenxia",
			"city_id": 411200,
			"py": "smx"
		}, {
			"name": "三明",
			"city_pinyin": "sanming",
			"city_id": 350400,
			"py": "sm"
		}, {
			"name": "三沙",
			"city_pinyin": "sansha",
			"city_id": 460300,
			"py": "ss"
		}, {
			"name": "三亚",
			"city_pinyin": "sanya",
			"city_id": 460200,
			"py": "sy"
		}, {
			"name": "三原",
			"city_pinyin": "sanyuan",
			"city_id": 610422,
			"py": "sy"
		}, {
			"name": "沙河市",
			"city_pinyin": "shaheshi",
			"city_id": 130582,
			"py": "shs"
		}, {
			"name": "商城",
			"city_pinyin": "shangcheng",
			"city_id": 411524,
			"py": "sc"
		}, {
			"name": "上高",
			"city_pinyin": "shanggao",
			"city_id": 360923,
			"py": "sg"
		}, {
			"name": "上海",
			"city_pinyin": "shanghai",
			"city_id": 310100,
			"py": "sh"
		}, {
			"name": "商洛",
			"city_pinyin": "shangluo",
			"city_id": 611000,
			"py": "sl"
		}, {
			"name": "商丘",
			"city_pinyin": "shangqiu",
			"city_id": 411400,
			"py": "sq"
		}, {
			"name": "上饶",
			"city_pinyin": "shangrao",
			"city_id": 361100,
			"py": "sr"
		}, {
			"name": "上虞市",
			"city_pinyin": "shangyushi",
			"city_id": 330682,
			"py": "sys"
		}, {
			"name": "尚志市",
			"city_pinyin": "shangzhishi",
			"city_id": 230183,
			"py": "szs"
		}, {
			"name": "汕头",
			"city_pinyin": "shantou",
			"city_id": 440500,
			"py": "st"
		}, {
			"name": "汕尾",
			"city_pinyin": "shanwei",
			"city_id": 441500,
			"py": "sw"
		}, {
			"name": "陕州",
			"city_pinyin": "shanzhou",
			"city_id": 411222,
			"py": "sz"
		}, {
			"name": "韶关",
			"city_pinyin": "shaoguan",
			"city_id": 440200,
			"py": "sg"
		}, {
			"name": "韶山市",
			"city_pinyin": "shaoshanshi",
			"city_id": 430382,
			"py": "sss"
		}, {
			"name": "邵武市",
			"city_pinyin": "shaowushi",
			"city_id": 350781,
			"py": "sws"
		}, {
			"name": "绍兴",
			"city_pinyin": "shaoxing",
			"city_id": 330600,
			"py": "sx"
		}, {
			"name": "邵阳",
			"city_pinyin": "shaoyang",
			"city_id": 430500,
			"py": "sy"
		}, {
			"name": "沙湾",
			"city_pinyin": "shawan",
			"city_id": 654223,
			"py": "sw"
		}, {
			"name": "什邡市",
			"city_pinyin": "shenfangshi",
			"city_id": 510682,
			"py": "sfs"
		}, {
			"name": "嵊州市",
			"city_pinyin": "shengzhoushi",
			"city_id": 330683,
			"py": "szs"
		}, {
			"name": "沈阳",
			"city_pinyin": "shenyang",
			"city_id": 210100,
			"py": "sy"
		}, {
			"name": "深圳",
			"city_pinyin": "shenzhen",
			"city_id": 440300,
			"py": "sz"
		}, {
			"name": "深州市",
			"city_pinyin": "shenzhoushi",
			"city_id": 131182,
			"py": "szs"
		}, {
			"name": "石城",
			"city_pinyin": "shicheng",
			"city_id": 360735,
			"py": "sc"
		}, {
			"name": "石河子",
			"city_pinyin": "shihezi",
			"city_id": 6590011,
			"py": "shz"
		}, {
			"name": "石河子市",
			"city_pinyin": "shihezishi",
			"city_id": 659001,
			"py": "shzs"
		}, {
			"name": "石家庄",
			"city_pinyin": "shijiazhuang",
			"city_id": 130100,
			"py": "sjz"
		}, {
			"name": "石狮",
			"city_pinyin": "shishi",
			"city_id": 350581,
			"py": "ss"
		}, {
			"name": "石首市",
			"city_pinyin": "shishoushi",
			"city_id": 421081,
			"py": "sss"
		}, {
			"name": "始兴",
			"city_pinyin": "shixiang",
			"city_id": 440222,
			"py": "sx"
		}, {
			"name": "十堰",
			"city_pinyin": "shiyan",
			"city_id": 420300,
			"py": "sy"
		}, {
			"name": "石嘴山",
			"city_pinyin": "shizuishan",
			"city_id": 640200,
			"py": "szs"
		}, {
			"name": "寿光市",
			"city_pinyin": "shouguangshi",
			"city_id": 370783,
			"py": "sgs"
		}, {
			"name": "双城市",
			"city_pinyin": "shuangchengshi",
			"city_id": 230182,
			"py": "scs"
		}, {
			"name": "双辽市",
			"city_pinyin": "shuangliaoshi",
			"city_id": 220382,
			"py": "sls"
		}, {
			"name": "双阳",
			"city_pinyin": "shuangyang",
			"city_id": 220112,
			"py": "sy"
		}, {
			"name": "双鸭山",
			"city_pinyin": "shuangyashan",
			"city_id": 230500,
			"py": "sys"
		}, {
			"name": "舒兰市",
			"city_pinyin": "shulanshi",
			"city_id": 220283,
			"py": "sls"
		}, {
			"name": "朔州",
			"city_pinyin": "shuozhou",
			"city_id": 140600,
			"py": "sz"
		}, {
			"name": "四会市",
			"city_pinyin": "sihuishi",
			"city_id": 441284,
			"py": "shs"
		}, {
			"name": "思南",
			"city_pinyin": "sinan",
			"city_id": 520624,
			"py": "sn"
		}, {
			"name": "四平",
			"city_pinyin": "siping",
			"city_id": 220300,
			"py": "sp"
		}, {
			"name": "泗水",
			"city_pinyin": "sishui",
			"city_id": 370831,
			"py": "ss"
		}, {
			"name": "松溪",
			"city_pinyin": "songxi",
			"city_id": 350724,
			"py": "sx"
		}, {
			"name": "松原",
			"city_pinyin": "songyuan",
			"city_id": 220700,
			"py": "sy"
		}, {
			"name": "松滋市",
			"city_pinyin": "songzishi",
			"city_id": 421087,
			"py": "szs"
		}, {
			"name": "遂昌",
			"city_pinyin": "suichang",
			"city_id": 331123,
			"py": "sc"
		}, {
			"name": "遂川",
			"city_pinyin": "suichuan",
			"city_id": 360827,
			"py": "sc"
		}, {
			"name": "绥芬河市",
			"city_pinyin": "suifenheshi",
			"city_id": 231081,
			"py": "sfhs"
		}, {
			"name": "绥化",
			"city_pinyin": "suihua",
			"city_id": 231200,
			"py": "sh"
		}, {
			"name": "绥棱",
			"city_pinyin": "suileng",
			"city_id": 231226,
			"py": "sl"
		}, {
			"name": "遂宁",
			"city_pinyin": "suining",
			"city_id": 510900,
			"py": "sn"
		}, {
			"name": "绥宁",
			"city_pinyin": "suining",
			"city_id": 430527,
			"py": "sn"
		}, {
			"name": "遂平",
			"city_pinyin": "suiping",
			"city_id": 411728,
			"py": "sp"
		}, {
			"name": "绥阳",
			"city_pinyin": "suiyang",
			"city_id": 520323,
			"py": "sy"
		}, {
			"name": "随州",
			"city_pinyin": "suizhou",
			"city_id": 421300,
			"py": "sz"
		}, {
			"name": "肃宁",
			"city_pinyin": "suning",
			"city_id": 130926,
			"py": "sn"
		}, {
			"name": "宿迁",
			"city_pinyin": "suqian",
			"city_id": 321300,
			"py": "sq"
		}, {
			"name": "宿松",
			"city_pinyin": "susong",
			"city_id": 340826,
			"py": "ss"
		}, {
			"name": "苏州",
			"city_pinyin": "suzhou",
			"city_id": 320500,
			"py": "sz"
		}, {
			"name": "宿州",
			"city_pinyin": "suzhou",
			"city_id": 341300,
			"py": "sz"
		}, ]
	}, {
		"letter": "T",
		"data": [{
			"name": "塔城市",
			"city_pinyin": "tachengshi",
			"city_id": 654201,
			"py": "tcs"
		}, {
			"name": "泰安",
			"city_pinyin": "taian",
			"city_id": 370900,
			"py": "ta"
		}, {
			"name": "台安",
			"city_pinyin": "taian",
			"city_id": 210321,
			"py": "ta"
		}, {
			"name": "台北",
			"city_pinyin": "taibei",
			"city_id": 710001,
			"py": "tb"
		}, {
			"name": "太仓",
			"city_pinyin": "taicang",
			"city_id": 320585,
			"py": "tc"
		}, {
			"name": "太谷",
			"city_pinyin": "taigu",
			"city_id": 140726,
			"py": "tg"
		}, {
			"name": "太湖",
			"city_pinyin": "taihu",
			"city_id": 340825,
			"py": "th"
		}, {
			"name": "台南",
			"city_pinyin": "tainan",
			"city_id": 710400,
			"py": "tn"
		}, {
			"name": "台前",
			"city_pinyin": "taiqian",
			"city_id": 410927,
			"py": "tq"
		}, {
			"name": "台山市",
			"city_pinyin": "taishanshi",
			"city_id": 440781,
			"py": "tss"
		}, {
			"name": "泰兴市",
			"city_pinyin": "taixingshi",
			"city_id": 321283,
			"py": "txs"
		}, {
			"name": "太原",
			"city_pinyin": "taiyuan",
			"city_id": 140100,
			"py": "ty"
		}, {
			"name": "台中",
			"city_pinyin": "taizhong",
			"city_id": 710300,
			"py": "tz"
		}, {
			"name": "泰州",
			"city_pinyin": "taizhou",
			"city_id": 321200,
			"py": "tz"
		}, {
			"name": "台州",
			"city_pinyin": "taizhou2",
			"city_id": 331000,
			"py": "tz"
		}, {
			"name": "唐山",
			"city_pinyin": "tangshan",
			"city_id": 130200,
			"py": "ts"
		}, {
			"name": "汤阴",
			"city_pinyin": "tangyin",
			"city_id": 410523,
			"py": "ty"
		}, {
			"name": "洮南市",
			"city_pinyin": "taonanshi",
			"city_id": 220881,
			"py": "tns"
		}, {
			"name": "桃园",
			"city_pinyin": "taoyuan",
			"city_id": 710600,
			"py": "ty"
		}, {
			"name": "滕州市",
			"city_pinyin": "tengzhoushi",
			"city_id": 370481,
			"py": "tzs"
		}, {
			"name": "天长市",
			"city_pinyin": "tianchangshi",
			"city_id": 341181,
			"py": "tcs"
		}, {
			"name": "天津",
			"city_pinyin": "tianjin",
			"city_id": 120100,
			"py": "tj"
		}, {
			"name": "天门",
			"city_pinyin": "tianmen",
			"city_id": 4290061,
			"py": "tm"
		}, {
			"name": "天门市",
			"city_pinyin": "tianmenshi",
			"city_id": 429006,
			"py": "tms"
		}, {
			"name": "天水",
			"city_pinyin": "tianshui",
			"city_id": 620500,
			"py": "ts"
		}, {
			"name": "铁岭",
			"city_pinyin": "tieling",
			"city_id": 211200,
			"py": "tl"
		}, {
			"name": "铁力市",
			"city_pinyin": "tielishi",
			"city_id": 230781,
			"py": "tls"
		}, {
			"name": "铁门关",
			"city_pinyin": "tiemenguan",
			"city_id": 659006,
			"py": "tmg"
		}, {
			"name": "桐柏",
			"city_pinyin": "tongbo",
			"city_id": 411330,
			"py": "tb"
		}, {
			"name": "通城",
			"city_pinyin": "tongcheng",
			"city_id": 421222,
			"py": "tc"
		}, {
			"name": "桐城市",
			"city_pinyin": "tongchengshi",
			"city_id": 340881,
			"py": "tcs"
		}, {
			"name": "铜川",
			"city_pinyin": "tongchuan",
			"city_id": 610200,
			"py": "tc"
		}, {
			"name": "通海",
			"city_pinyin": "tonghai",
			"city_id": 530423,
			"py": "th"
		}, {
			"name": "通化",
			"city_pinyin": "tonghua",
			"city_id": 220500,
			"py": "th"
		}, {
			"name": "同江",
			"city_pinyin": "tongjiang",
			"city_id": 230881,
			"py": "tj"
		}, {
			"name": "通江",
			"city_pinyin": "tongjiang",
			"city_id": 511921,
			"py": "tj"
		}, {
			"name": "通辽",
			"city_pinyin": "tongliao",
			"city_id": 150500,
			"py": "tl"
		}, {
			"name": "铜陵",
			"city_pinyin": "tongling",
			"city_id": 340700,
			"py": "tl"
		}, {
			"name": "铜仁",
			"city_pinyin": "tongren",
			"city_id": 520600,
			"py": "tr"
		}, {
			"name": "通山",
			"city_pinyin": "tongshan",
			"city_id": 421224,
			"py": "ts"
		}, {
			"name": "桐乡市",
			"city_pinyin": "tongxiangshi",
			"city_id": 330483,
			"py": "txs"
		}, {
			"name": "通榆",
			"city_pinyin": "tongyu",
			"city_id": 220822,
			"py": "ty"
		}, {
			"name": "团风",
			"city_pinyin": "tuanfeng",
			"city_id": 421121,
			"py": "tf"
		}, {
			"name": "吐鲁番",
			"city_pinyin": "tulufan",
			"city_id": 652100,
			"py": "tlf"
		}, {
			"name": "图们市",
			"city_pinyin": "tumenshi",
			"city_id": 222402,
			"py": "tms"
		}, {
			"name": "托克托",
			"city_pinyin": "tuoketuo",
			"city_id": 150122,
			"py": "tkt"
		}, {
			"name": "突泉",
			"city_pinyin": "tuquan",
			"city_id": 152224,
			"py": "tq"
		}]
	}, {
		"letter": "W",
		"data": [{
			"name": "瓦房店市",
			"city_pinyin": "wafangdianshi",
			"city_id": 210281,
			"py": "wfds"
		}, {
			"name": "望城",
			"city_pinyin": "wangcheng",
			"city_id": 430112,
			"py": "wc"
		}, {
			"name": "望奎",
			"city_pinyin": "wangkui",
			"city_id": 231221,
			"py": "wk"
		}, {
			"name": "万年",
			"city_pinyin": "wannian",
			"city_id": 361129,
			"py": "wn"
		}, {
			"name": "万宁",
			"city_pinyin": "wanning",
			"city_id": 4690061,
			"py": "wn"
		}, {
			"name": "万宁市",
			"city_pinyin": "wanningshi",
			"city_id": 469006,
			"py": "wns"
		}, {
			"name": "万全",
			"city_pinyin": "wanquan",
			"city_id": 130729,
			"py": "wq"
		}, {
			"name": "万荣",
			"city_pinyin": "wanrong",
			"city_id": 140822,
			"py": "wr"
		}, {
			"name": "万源",
			"city_pinyin": "wanyuan",
			"city_id": 511781,
			"py": "wy"
		}, {
			"name": "万载",
			"city_pinyin": "wanzai",
			"city_id": 360922,
			"py": "wz"
		}, {
			"name": "潍坊",
			"city_pinyin": "weifang",
			"city_id": 370700,
			"py": "wf"
		}, {
			"name": "威海",
			"city_pinyin": "weihai",
			"city_id": 371000,
			"py": "wh"
		}, {
			"name": "卫辉市",
			"city_pinyin": "weihuishi",
			"city_id": 410781,
			"py": "whs"
		}, {
			"name": "渭南",
			"city_pinyin": "weinan",
			"city_id": 610500,
			"py": "wn"
		}, {
			"name": "文昌",
			"city_pinyin": "wenchang",
			"city_id": 469005,
			"py": "wc"
		}, {
			"name": "文登市",
			"city_pinyin": "wendengshi",
			"city_id": 371081,
			"py": "wds"
		}, {
			"name": "翁源",
			"city_pinyin": "wengyuan",
			"city_id": 440229,
			"py": "wy"
		}, {
			"name": "文山州",
			"city_pinyin": "wenshanzhou",
			"city_id": 532600,
			"py": "wsz"
		}, {
			"name": "温州",
			"city_pinyin": "wenzhou",
			"city_id": 330300,
			"py": "wz"
		}, {
			"name": "武安市",
			"city_pinyin": "wuanshi",
			"city_id": 130481,
			"py": "was"
		}, {
			"name": "五常市",
			"city_pinyin": "wuchangshi",
			"city_id": 230184,
			"py": "wcs"
		}, {
			"name": "吴川市",
			"city_pinyin": "wuchuanshi",
			"city_id": 440883,
			"py": "wcs"
		}, {
			"name": "五大连池",
			"city_pinyin": "wudalianchi",
			"city_id": 231182,
			"py": "wdlc"
		}, {
			"name": "舞钢",
			"city_pinyin": "wugang",
			"city_id": 410481,
			"py": "wg"
		}, {
			"name": "武冈市",
			"city_pinyin": "wugangshi",
			"city_id": 430581,
			"py": "wgs"
		}, {
			"name": "乌海",
			"city_pinyin": "wuhai",
			"city_id": 150300,
			"py": "wh"
		}, {
			"name": "武汉",
			"city_pinyin": "wuhan",
			"city_id": 420100,
			"py": "wh"
		}, {
			"name": "芜湖",
			"city_pinyin": "wuhu",
			"city_id": 340200,
			"py": "wh"
		}, {
			"name": "无极",
			"city_pinyin": "wuji",
			"city_id": 130130,
			"py": "wj"
		}, {
			"name": "吴江",
			"city_pinyin": "wujiang",
			"city_id": 320509,
			"py": "wj"
		}, {
			"name": "五家渠",
			"city_pinyin": "wujiaqu",
			"city_id": 659004,
			"py": "wjq"
		}, {
			"name": "乌兰察布",
			"city_pinyin": "wulanchabu",
			"city_id": 150900,
			"py": "wlcb"
		}, {
			"name": "乌兰浩特市",
			"city_pinyin": "wulanhaoteshi",
			"city_id": 152201,
			"py": "wlhts"
		}, {
			"name": "五莲",
			"city_pinyin": "wulian",
			"city_id": 371121,
			"py": "wl"
		}, {
			"name": "乌鲁木齐",
			"city_pinyin": "wulumuqi",
			"city_id": 650100,
			"py": "wlmq"
		}, {
			"name": "武鸣",
			"city_pinyin": "wuming",
			"city_id": 450122,
			"py": "wm"
		}, {
			"name": "武宁",
			"city_pinyin": "wuning",
			"city_id": 360423,
			"py": "wn"
		}, {
			"name": "武胜",
			"city_pinyin": "wusheng",
			"city_id": 511622,
			"py": "ws"
		}, {
			"name": "乌苏市",
			"city_pinyin": "wusushi",
			"city_id": 654202,
			"py": "wss"
		}, {
			"name": "武威",
			"city_pinyin": "wuwei",
			"city_id": 620600,
			"py": "ww"
		}, {
			"name": "无锡",
			"city_pinyin": "wuxi",
			"city_id": 320200,
			"py": "wx"
		}, {
			"name": "武穴市",
			"city_pinyin": "wuxueshi",
			"city_id": 421182,
			"py": "wxs"
		}, {
			"name": "武夷山",
			"city_pinyin": "wuyishan",
			"city_id": 350782,
			"py": "wys"
		}, {
			"name": "五原",
			"city_pinyin": "wuyuan",
			"city_id": 150821,
			"py": "wy"
		}, {
			"name": "五指山",
			"city_pinyin": "wuzhishan",
			"city_id": 469001,
			"py": "wzs"
		}, {
			"name": "吴忠",
			"city_pinyin": "wuzhong",
			"city_id": 640300,
			"py": "wz"
		}, {
			"name": "梧州",
			"city_pinyin": "wuzhou",
			"city_id": 450400,
			"py": "wz"
		}]
	}, {
		"letter": "X",
		"data": [{
			"name": "厦门",
			"city_pinyin": "xiamen",
			"city_id": 350200,
			"py": "xm"
		}, {
			"name": "西安",
			"city_pinyin": "xian",
			"city_id": 610100,
			"py": "xa"
		}, {
			"name": "项城市",
			"city_pinyin": "xiangchengshi",
			"city_id": 411681,
			"py": "xcs"
		}, {
			"name": "襄汾",
			"city_pinyin": "xiangfen",
			"city_id": 141023,
			"py": "xf"
		}, {
			"name": "祥符",
			"city_pinyin": "xiangfu",
			"city_id": 410224,
			"py": "xf"
		}, {
			"name": "香港",
			"city_pinyin": "xianggang",
			"city_id": 810001,
			"py": "xg"
		}, {
			"name": "香格里拉市",
			"city_pinyin": "xianggelilashi",
			"city_id": 533421,
			"py": "xglls"
		}, {
			"name": "湘潭",
			"city_pinyin": "xiangtan",
			"city_id": 430300,
			"py": "xt"
		}, {
			"name": "湘乡市",
			"city_pinyin": "xiangxiangshi",
			"city_id": 430381,
			"py": "xxs"
		}, {
			"name": "湘西土家族苗族自治州",
			"city_pinyin": "xiangxitujiazumiaozuzizhizhou",
			"city_id": 433100,
			"py": "xxtjzmzzzz"
		}, {
			"name": "襄阳",
			"city_pinyin": "xiangyang",
			"city_id": 420600,
			"py": "xy"
		}, {
			"name": "襄垣",
			"city_pinyin": "xiangyuan",
			"city_id": 140423,
			"py": "xy"
		}, {
			"name": "咸宁",
			"city_pinyin": "xianning",
			"city_id": 421200,
			"py": "xn"
		}, {
			"name": "仙桃",
			"city_pinyin": "xiantao",
			"city_id": 4290041,
			"py": "xt"
		}, {
			"name": "仙桃市",
			"city_pinyin": "xiantaoshi",
			"city_id": 429004,
			"py": "xts"
		}, {
			"name": "咸阳",
			"city_pinyin": "xianyang",
			"city_id": 610400,
			"py": "xy"
		}, {
			"name": "孝感",
			"city_pinyin": "xiaogan",
			"city_id": 420900,
			"py": "xg"
		}, {
			"name": "孝义市",
			"city_pinyin": "xiaoyishi",
			"city_id": 141181,
			"py": "xys"
		}, {
			"name": "西昌",
			"city_pinyin": "xichang",
			"city_id": 513401,
			"py": "xc"
		}, {
			"name": "西充",
			"city_pinyin": "xichong",
			"city_id": 511325,
			"py": "xc"
		}, {
			"name": "西丰",
			"city_pinyin": "xifeng",
			"city_id": 211223,
			"py": "xf"
		}, {
			"name": "锡林浩特市",
			"city_pinyin": "xilinhaoteshi",
			"city_id": 152502,
			"py": "xlhts"
		}, {
			"name": "新北",
			"city_pinyin": "xinbei",
			"city_id": 710200,
			"py": "xb"
		}, {
			"name": "新丰",
			"city_pinyin": "xinfeng",
			"city_id": 440233,
			"py": "xf"
		}, {
			"name": "新干",
			"city_pinyin": "xingan",
			"city_id": 360824,
			"py": "xg"
		}, {
			"name": "兴城市",
			"city_pinyin": "xingchengshi",
			"city_id": 211481,
			"py": "xcs"
		}, {
			"name": "兴化市",
			"city_pinyin": "xinghuashi",
			"city_id": 321281,
			"py": "xhs"
		}, {
			"name": "兴宁市",
			"city_pinyin": "xingningshi",
			"city_id": 441481,
			"py": "xns"
		}, {
			"name": "兴平",
			"city_pinyin": "xingping",
			"city_id": 610481,
			"py": "xp"
		}, {
			"name": "邢台",
			"city_pinyin": "xingtai",
			"city_id": 130500,
			"py": "xt"
		}, {
			"name": "荥阳市",
			"city_pinyin": "xingyangshi",
			"city_id": 410182,
			"py": "xys"
		}, {
			"name": "兴义市",
			"city_pinyin": "xingyishi",
			"city_id": 522301,
			"py": "xys"
		}, {
			"name": "星子",
			"city_pinyin": "xingzi",
			"city_id": 360427,
			"py": "xz"
		}, {
			"name": "西宁",
			"city_pinyin": "xining",
			"city_id": 630100,
			"py": "xn"
		}, {
			"name": "新绛",
			"city_pinyin": "xinjiang",
			"city_id": 140825,
			"py": "xj"
		}, {
			"name": "辛集市",
			"city_pinyin": "xinjishi",
			"city_id": 130181,
			"py": "xjs"
		}, {
			"name": "新乐市",
			"city_pinyin": "xinleshi",
			"city_id": 130184,
			"py": "xls"
		}, {
			"name": "新民市",
			"city_pinyin": "xinminshi",
			"city_id": 210181,
			"py": "xms"
		}, {
			"name": "新密市",
			"city_pinyin": "xinmishi",
			"city_id": 410183,
			"py": "xms"
		}, {
			"name": "新泰市",
			"city_pinyin": "xintaishi",
			"city_id": 370982,
			"py": "xts"
		}, {
			"name": "新田",
			"city_pinyin": "xintian",
			"city_id": 431128,
			"py": "xt"
		}, {
			"name": "新乡",
			"city_pinyin": "xinxiang",
			"city_id": 410700,
			"py": "xx"
		}, {
			"name": "新兴",
			"city_pinyin": "xinxing",
			"city_id": 445321,
			"py": "xx"
		}, {
			"name": "信阳",
			"city_pinyin": "xinyang",
			"city_id": 411500,
			"py": "xy"
		}, {
			"name": "信宜市",
			"city_pinyin": "xinyishi",
			"city_id": 440983,
			"py": "xys"
		}, {
			"name": "新沂市",
			"city_pinyin": "xinyishi",
			"city_id": 320381,
			"py": "xys"
		}, {
			"name": "新余",
			"city_pinyin": "xinyu",
			"city_id": 360500,
			"py": "xy"
		}, {
			"name": "新郑市",
			"city_pinyin": "xinzhengshi",
			"city_id": 410184,
			"py": "xzs"
		}, {
			"name": "忻州",
			"city_pinyin": "xinzhou",
			"city_id": 140900,
			"py": "xz"
		}, {
			"name": "新洲",
			"city_pinyin": "xinzhou",
			"city_id": 420117,
			"py": "xz"
		}, {
			"name": "新竹",
			"city_pinyin": "xinzhu",
			"city_id": 711800,
			"py": "xz"
		}, {
			"name": "西双版纳傣族自治州",
			"city_pinyin": "xishuangbannadaizuzizhizhou",
			"city_id": 532800,
			"py": "xsbndzzzz"
		}, {
			"name": "习水",
			"city_pinyin": "xishui",
			"city_id": 520330,
			"py": "xs"
		}, {
			"name": "修武",
			"city_pinyin": "xiuwu",
			"city_id": 410821,
			"py": "xw"
		}, {
			"name": "宣城",
			"city_pinyin": "xuancheng",
			"city_id": 341800,
			"py": "xc"
		}, {
			"name": "宣威市",
			"city_pinyin": "xuanweishi",
			"city_id": 530381,
			"py": "xws"
		}, {
			"name": "许昌",
			"city_pinyin": "xuchang",
			"city_id": 411000,
			"py": "xc"
		}, {
			"name": "虚拟城市",
			"city_pinyin": "xunichengs",
			"city_id": 376600,
			"py": "xncs"
		}, {
			"name": "寻乌",
			"city_pinyin": "xunwu",
			"city_id": 360734,
			"py": "xw"
		}, {
			"name": "叙永",
			"city_pinyin": "xuyong",
			"city_id": 510524,
			"py": "xy"
		}, {
			"name": "徐州",
			"city_pinyin": "xuzhou",
			"city_id": 320300,
			"py": "xz"
		}]
	}, {
		"letter": "Y",
		"data": [{
			"name": "雅安",
			"city_pinyin": "yaan",
			"city_id": 511800,
			"py": "ya"
		}, {
			"name": "牙克石市",
			"city_pinyin": "yakeshishi",
			"city_id": 150782,
			"py": "ykss"
		}, {
			"name": "延安",
			"city_pinyin": "yanan",
			"city_id": 610600,
			"py": "ya"
		}, {
			"name": "延边朝鲜族自治州",
			"city_pinyin": "yanbianchaoxianzuzizhizhou",
			"city_id": 222400,
			"py": "ybcxzzzz"
		}, {
			"name": "盐城",
			"city_pinyin": "yancheng",
			"city_id": 320900,
			"py": "yc"
		}, {
			"name": "盐池",
			"city_pinyin": "yanchi",
			"city_id": 640323,
			"py": "yc"
		}, {
			"name": "阳春市",
			"city_pinyin": "yangchunshi",
			"city_id": 441781,
			"py": "ycs"
		}, {
			"name": "阳江",
			"city_pinyin": "yangjiang",
			"city_id": 441700,
			"py": "yj"
		}, {
			"name": "杨陵",
			"city_pinyin": "yangling",
			"city_id": 610403,
			"py": "yl"
		}, {
			"name": "阳泉",
			"city_pinyin": "yangquan",
			"city_id": 140300,
			"py": "yq"
		}, {
			"name": "阳朔",
			"city_pinyin": "yangshuo",
			"city_id": 450321,
			"py": "ys"
		}, {
			"name": "阳西",
			"city_pinyin": "yangxi",
			"city_id": 441721,
			"py": "yx"
		}, {
			"name": "扬中市",
			"city_pinyin": "yangzhongshi",
			"city_id": 321182,
			"py": "yzs"
		}, {
			"name": "扬州",
			"city_pinyin": "yangzhou",
			"city_id": 321000,
			"py": "yz"
		}, {
			"name": "延吉",
			"city_pinyin": "yanji",
			"city_id": 222401,
			"py": "yj"
		}, {
			"name": "延津",
			"city_pinyin": "yanjin",
			"city_id": 410726,
			"py": "yj"
		}, {
			"name": "阎良",
			"city_pinyin": "yanliang",
			"city_id": 610114,
			"py": "yl"
		}, {
			"name": "偃师市",
			"city_pinyin": "yanshishi",
			"city_id": 410381,
			"py": "yss"
		}, {
			"name": "烟台",
			"city_pinyin": "yantai",
			"city_id": 370600,
			"py": "yt"
		}, {
			"name": "盐亭",
			"city_pinyin": "yanting",
			"city_id": 510723,
			"py": "yt"
		}, {
			"name": "兖州市",
			"city_pinyin": "yanzhoushi",
			"city_id": 370882,
			"py": "yzs"
		}, {
			"name": "依安",
			"city_pinyin": "yian",
			"city_id": 230223,
			"py": "ya"
		}, {
			"name": "宜宾",
			"city_pinyin": "yibin",
			"city_id": 511500,
			"py": "yb"
		}, {
			"name": "宜昌",
			"city_pinyin": "yichang",
			"city_id": 420500,
			"py": "yc"
		}, {
			"name": "宜城市",
			"city_pinyin": "yichengshi",
			"city_id": 420684,
			"py": "ycs"
		}, {
			"name": "宜春",
			"city_pinyin": "yichun",
			"city_id": 360900,
			"py": "yc"
		}, {
			"name": "伊春市",
			"city_pinyin": "yichunshi",
			"city_id": 230700,
			"py": "ycs"
		}, {
			"name": "宜都市",
			"city_pinyin": "yidoushi",
			"city_id": 420581,
			"py": "yds"
		}, {
			"name": "宜丰",
			"city_pinyin": "yifeng",
			"city_id": 360924,
			"py": "yf"
		}, {
			"name": "伊犁哈萨克自治州",
			"city_pinyin": "yilihasakezizhizhou",
			"city_id": 654000,
			"py": "ylhskzzz"
		}, {
			"name": "义马",
			"city_pinyin": "yima",
			"city_id": 411281,
			"py": "ym"
		}, {
			"name": "银川",
			"city_pinyin": "yinchuan",
			"city_id": 640100,
			"py": "yc"
		}, {
			"name": "应城市",
			"city_pinyin": "yingchengshi",
			"city_id": 420981,
			"py": "ycs"
		}, {
			"name": "英德市",
			"city_pinyin": "yingdeshi",
			"city_id": 441881,
			"py": "yds"
		}, {
			"name": "营口",
			"city_pinyin": "yingkou",
			"city_id": 210800,
			"py": "yk"
		}, {
			"name": "英山",
			"city_pinyin": "yingshan",
			"city_id": 421124,
			"py": "ys"
		}, {
			"name": "鹰潭",
			"city_pinyin": "yingtan",
			"city_id": 360600,
			"py": "yt"
		}, {
			"name": "伊宁市",
			"city_pinyin": "yiningshi",
			"city_id": 654002,
			"py": "yns"
		}, {
			"name": "义乌",
			"city_pinyin": "yiwu",
			"city_id": 330782,
			"py": "yw"
		}, {
			"name": "宜兴",
			"city_pinyin": "yixing",
			"city_id": 320282,
			"py": "yx"
		}, {
			"name": "益阳",
			"city_pinyin": "yiyang",
			"city_id": 430900,
			"py": "yy"
		}, {
			"name": "弋阳",
			"city_pinyin": "yiyang",
			"city_id": 361126,
			"py": "yy"
		}, {
			"name": "宜阳",
			"city_pinyin": "yiyang",
			"city_id": 410327,
			"py": "yy"
		}, {
			"name": "仪征市",
			"city_pinyin": "yizhengshi",
			"city_id": 321081,
			"py": "yzs"
		}, {
			"name": "宜州",
			"city_pinyin": "yizhou",
			"city_id": 451281,
			"py": "yz"
		}, {
			"name": "永安市",
			"city_pinyin": "yonganshi",
			"city_id": 350481,
			"py": "yas"
		}, {
			"name": "永城市",
			"city_pinyin": "yongchengshi",
			"city_id": 411481,
			"py": "ycs"
		}, {
			"name": "永丰",
			"city_pinyin": "yongfeng",
			"city_id": 360825,
			"py": "yf"
		}, {
			"name": "永吉",
			"city_pinyin": "yongji",
			"city_id": 220221,
			"py": "yj"
		}, {
			"name": "永济市",
			"city_pinyin": "yongjishi",
			"city_id": 140881,
			"py": "yjs"
		}, {
			"name": "永清",
			"city_pinyin": "yongqing",
			"city_id": 131023,
			"py": "yq"
		}, {
			"name": "永泰",
			"city_pinyin": "yongtai",
			"city_id": 350125,
			"py": "yt"
		}, {
			"name": "永州",
			"city_pinyin": "yongzhou",
			"city_id": 431100,
			"py": "yz"
		}, {
			"name": "远安",
			"city_pinyin": "yuanan",
			"city_id": 420525,
			"py": "ya"
		}, {
			"name": "元宝山",
			"city_pinyin": "yuanbaoshan",
			"city_id": 150403,
			"py": "ybs"
		}, {
			"name": "沅江市",
			"city_pinyin": "yuanjiangshi",
			"city_id": 430981,
			"py": "yjs"
		}, {
			"name": "原平市",
			"city_pinyin": "yuanpingshi",
			"city_id": 140981,
			"py": "yps"
		}, {
			"name": "禹城市",
			"city_pinyin": "yuchengshi",
			"city_id": 371482,
			"py": "ycs"
		}, {
			"name": "榆次",
			"city_pinyin": "yuci",
			"city_id": 140702,
			"py": "yc"
		}, {
			"name": "岳阳",
			"city_pinyin": "yueyang",
			"city_id": 430600,
			"py": "yy"
		}, {
			"name": "余江",
			"city_pinyin": "yujiang",
			"city_id": 360622,
			"py": "yj"
		}, {
			"name": "榆林",
			"city_pinyin": "yulin",
			"city_id": 610800,
			"py": "yl"
		}, {
			"name": "玉林",
			"city_pinyin": "yulin",
			"city_id": 450900,
			"py": "yl"
		}, {
			"name": "玉门市",
			"city_pinyin": "yumenshi",
			"city_id": 620981,
			"py": "yms"
		}, {
			"name": "运城",
			"city_pinyin": "yuncheng",
			"city_id": 140800,
			"py": "yc"
		}, {
			"name": "云浮",
			"city_pinyin": "yunfu",
			"city_id": 445300,
			"py": "yf"
		}, {
			"name": "筠连",
			"city_pinyin": "yunlian",
			"city_id": 511527,
			"py": "jl"
		}, {
			"name": "榆树市",
			"city_pinyin": "yushushi",
			"city_id": 220182,
			"py": "yss"
		}, {
			"name": "玉树市",
			"city_pinyin": "yushushi",
			"city_id": 632721,
			"py": "yss"
		}, {
			"name": "玉树藏族自治州",
			"city_pinyin": "yushuzangzuzizhizhou",
			"city_id": 632700,
			"py": "yszzzzz"
		}, {
			"name": "鱼台",
			"city_pinyin": "yutai",
			"city_id": 370827,
			"py": "yt"
		}, {
			"name": "玉溪",
			"city_pinyin": "yuxi",
			"city_id": 530400,
			"py": "yx"
		}, {
			"name": "榆中",
			"city_pinyin": "yuzhong",
			"city_id": 620123,
			"py": "yz"
		}, {
			"name": "禹州市",
			"city_pinyin": "yuzhoushi",
			"city_id": 411081,
			"py": "yzs"
		}]
	}, {
		"letter": "Z",
		"data": [{
			"name": "赞皇",
			"city_pinyin": "zanhuang",
			"city_id": 130129,
			"py": "zh"
		}, {
			"name": "枣强",
			"city_pinyin": "zaoqiang",
			"city_id": 131121,
			"py": "zq"
		}, {
			"name": "枣阳市",
			"city_pinyin": "zaoyangshi",
			"city_id": 420683,
			"py": "zys"
		}, {
			"name": "枣庄",
			"city_pinyin": "zaozhuang",
			"city_id": 370400,
			"py": "zz"
		}, {
			"name": "扎兰屯",
			"city_pinyin": "zhalantun",
			"city_id": 150783,
			"py": "zlt"
		}, {
			"name": "张北",
			"city_pinyin": "zhangbei",
			"city_id": 130722,
			"py": "zb"
		}, {
			"name": "张家港",
			"city_pinyin": "zhangjiagang",
			"city_id": 320582,
			"py": "zjg"
		}, {
			"name": "张家界",
			"city_pinyin": "zhangjiajie",
			"city_id": 430800,
			"py": "zjj"
		}, {
			"name": "张家口",
			"city_pinyin": "zhangjiakou",
			"city_id": 130700,
			"py": "zjk"
		}, {
			"name": "漳平",
			"city_pinyin": "zhangping",
			"city_id": 350881,
			"py": "zp"
		}, {
			"name": "樟树市",
			"city_pinyin": "zhangshushi",
			"city_id": 360982,
			"py": "zss"
		}, {
			"name": "彰武",
			"city_pinyin": "zhangwu",
			"city_id": 210922,
			"py": "zw"
		}, {
			"name": "张掖",
			"city_pinyin": "zhangye",
			"city_id": 620700,
			"py": "zy"
		}, {
			"name": "漳州",
			"city_pinyin": "zhangzhou",
			"city_id": 350600,
			"py": "zz"
		}, {
			"name": "湛江",
			"city_pinyin": "zhanjiang",
			"city_id": 440800,
			"py": "zj"
		}, {
			"name": "肇东市",
			"city_pinyin": "zhaodongshi",
			"city_id": 231282,
			"py": "zds"
		}, {
			"name": "肇庆",
			"city_pinyin": "zhaoqing",
			"city_id": 441200,
			"py": "zq"
		}, {
			"name": "昭通",
			"city_pinyin": "zhaotong",
			"city_id": 530600,
			"py": "zt"
		}, {
			"name": "肇源",
			"city_pinyin": "zhaoyuan",
			"city_id": 230622,
			"py": "zy"
		}, {
			"name": "招远市",
			"city_pinyin": "zhaoyuanshi",
			"city_id": 370685,
			"py": "zys"
		}, {
			"name": "政和",
			"city_pinyin": "zhenghe",
			"city_id": 350725,
			"py": "zh"
		}, {
			"name": "郑州",
			"city_pinyin": "zhengzhou",
			"city_id": 410100,
			"py": "zz"
		}, {
			"name": "镇江",
			"city_pinyin": "zhenjiang",
			"city_id": 321100,
			"py": "zj"
		}, {
			"name": "镇赉",
			"city_pinyin": "zhenlai",
			"city_id": 220821,
			"py": "zl"
		}, {
			"name": "枝江市",
			"city_pinyin": "zhijiangshi",
			"city_id": 420583,
			"py": "zjs"
		}, {
			"name": "中宁",
			"city_pinyin": "zhongning",
			"city_id": 640521,
			"py": "zn"
		}, {
			"name": "中山",
			"city_pinyin": "zhongshan",
			"city_id": 442000,
			"py": "zs"
		}, {
			"name": "中卫",
			"city_pinyin": "zhongwei",
			"city_id": 640500,
			"py": "zw"
		}, {
			"name": "钟祥市",
			"city_pinyin": "zhongxiangshi",
			"city_id": 420881,
			"py": "zxs"
		}, {
			"name": "周口",
			"city_pinyin": "zhoukou",
			"city_id": 411600,
			"py": "zk"
		}, {
			"name": "舟山",
			"city_pinyin": "zhoushan",
			"city_id": 330900,
			"py": "zs"
		}, {
			"name": "庄河市",
			"city_pinyin": "zhuangheshi",
			"city_id": 210283,
			"py": "zhs"
		}, {
			"name": "诸城市",
			"city_pinyin": "zhuchengshi",
			"city_id": 370782,
			"py": "zcs"
		}, {
			"name": "珠海",
			"city_pinyin": "zhuhai",
			"city_id": 440400,
			"py": "zh"
		}, {
			"name": "诸暨市",
			"city_pinyin": "zhujishi",
			"city_id": 330681,
			"py": "zjs"
		}, {
			"name": "驻马店",
			"city_pinyin": "zhumadian",
			"city_id": 411700,
			"py": "zmd"
		}, {
			"name": "涿鹿",
			"city_pinyin": "zhuolu",
			"city_id": 130731,
			"py": "zl"
		}, {
			"name": "涿州",
			"city_pinyin": "zhuozhou",
			"city_id": 130681,
			"py": "zz"
		}, {
			"name": "株洲",
			"city_pinyin": "zhuzhou",
			"city_id": 430200,
			"py": "zz"
		}, {
			"name": "淄博",
			"city_pinyin": "zibo",
			"city_id": 370300,
			"py": "zb"
		}, {
			"name": "自贡",
			"city_pinyin": "zigong",
			"city_id": 510300,
			"py": "zg"
		}, {
			"name": "秭归",
			"city_pinyin": "zigui",
			"city_id": 420527,
			"py": "zg"
		}, {
			"name": "梓潼",
			"city_pinyin": "zitong",
			"city_id": 510725,
			"py": "zt"
		}, {
			"name": "资兴市",
			"city_pinyin": "zixingshi",
			"city_id": 431081,
			"py": "zxs"
		}, {
			"name": "资阳",
			"city_pinyin": "ziyang",
			"city_id": 512000,
			"py": "zy"
		}, {
			"name": "邹城市",
			"city_pinyin": "zouchengshi",
			"city_id": 370883,
			"py": "zcs"
		}, {
			"name": "遵化市",
			"city_pinyin": "zunhuashi",
			"city_id": 130281,
			"py": "zhs"
		}, {
			"name": "遵义",
			"city_pinyin": "zunyi",
			"city_id": 520300,
			"py": "zy"
		}, ]
	}]
};

